version: "3.9"

services:
  db:
    build:
      context: ./control
      dockerfile: db.dockerfile
    image: spice-ledger-db
    container_name: spice-ledger-db
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: spice_ledger
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./control/app.dockerfile
    image: spice-ledger-app
    container_name: spice-ledger-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "50051:50051"

  rest:
    build:
      context: .
      dockerfile: ./rest/app.dockerfile
    image: spice-ledger-rest
    container_name: spice-ledger-rest
    depends_on:
      - app
    environment:
      - ACCOUNT_GRPC_URL=app:50051
      - PORT=8082
      - LOG_LEVEL=debug
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=admin
    ports:
      - "8082:8082"

  proxy:
    build:
      context: ./proxy
      dockerfile: app.dockerfile
    image: spice-ledger-proxy
    container_name: spice-ledger-proxy
    depends_on:
      - rest
      - app
    environment:
      - ACCOUNT_SERVICE_URL=http://rest:8082
      - GRAPHQL_GATEWAY_URL=http://gql-gateway:4000 # Placeholder for now
      - PROXY_PORT=80
      - LOG_LEVEL=debug
    ports:
      - "80:80"

volumes:
  mysql_data:
