// protoc --go_out=./pb --go-grpc_out=./pb market.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: market.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,3,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	TradeDate     string                 `protobuf:"bytes,7,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"` // YYYY-MM-DD
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // YYYY-MM-DD HH:MM:SS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Transaction) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Transaction) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PositionView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	TotalQty      float64                `protobuf:"fixed64,3,opt,name=total_qty,json=totalQty,proto3" json:"total_qty,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	AvgCost       float64                `protobuf:"fixed64,5,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	TodayPrice    float64                `protobuf:"fixed64,6,opt,name=today_price,json=todayPrice,proto3" json:"today_price,omitempty"`
	RealizedPnl   float64                `protobuf:"fixed64,7,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	UnrealizedPnl float64                `protobuf:"fixed64,8,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionView) Reset() {
	*x = PositionView{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionView) ProtoMessage() {}

func (x *PositionView) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionView.ProtoReflect.Descriptor instead.
func (*PositionView) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *PositionView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PositionView) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *PositionView) GetTotalQty() float64 {
	if x != nil {
		return x.TotalQty
	}
	return 0
}

func (x *PositionView) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *PositionView) GetAvgCost() float64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *PositionView) GetTodayPrice() float64 {
	if x != nil {
		return x.TodayPrice
	}
	return 0
}

func (x *PositionView) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *PositionView) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *PositionView) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	TradeDate     string                 `protobuf:"bytes,5,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *BuyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BuyRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *BuyRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

type BuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *BuyResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	TradeDate     string                 `protobuf:"bytes,5,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *SellRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SellRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *SellRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SellRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

type SellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellResponse) Reset() {
	*x = SellResponse{}
	mi := &file_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellResponse) ProtoMessage() {}

func (x *SellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellResponse.ProtoReflect.Descriptor instead.
func (*SellResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

func (x *SellResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetGradePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradePositionRequest) Reset() {
	*x = GetGradePositionRequest{}
	mi := &file_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradePositionRequest) ProtoMessage() {}

func (x *GetGradePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradePositionRequest.ProtoReflect.Descriptor instead.
func (*GetGradePositionRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{6}
}

func (x *GetGradePositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGradePositionRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

type GetGradePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionView          `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradePositionResponse) Reset() {
	*x = GetGradePositionResponse{}
	mi := &file_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradePositionResponse) ProtoMessage() {}

func (x *GetGradePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradePositionResponse.ProtoReflect.Descriptor instead.
func (*GetGradePositionResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{7}
}

func (x *GetGradePositionResponse) GetPosition() *PositionView {
	if x != nil {
		return x.Position
	}
	return nil
}

type GetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsRequest) Reset() {
	*x = GetPositionsRequest{}
	mi := &file_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsRequest) ProtoMessage() {}

func (x *GetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{8}
}

func (x *GetPositionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*PositionView        `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsResponse) Reset() {
	*x = GetPositionsResponse{}
	mi := &file_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsResponse) ProtoMessage() {}

func (x *GetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{9}
}

func (x *GetPositionsResponse) GetPositions() []*PositionView {
	if x != nil {
		return x.Positions
	}
	return nil
}

type ListGradeTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Skip          uint32                 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradeTransactionsRequest) Reset() {
	*x = ListGradeTransactionsRequest{}
	mi := &file_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradeTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradeTransactionsRequest) ProtoMessage() {}

func (x *ListGradeTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradeTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListGradeTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{10}
}

func (x *ListGradeTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListGradeTransactionsRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *ListGradeTransactionsRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListGradeTransactionsRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListGradeTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradeTransactionsResponse) Reset() {
	*x = ListGradeTransactionsResponse{}
	mi := &file_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradeTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradeTransactionsResponse) ProtoMessage() {}

func (x *ListGradeTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradeTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListGradeTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{11}
}

func (x *ListGradeTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Skip          uint32                 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{12}
}

func (x *ListTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTransactionsRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListTransactionsRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{13}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetMarketMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketMetricsRequest) Reset() {
	*x = GetMarketMetricsRequest{}
	mi := &file_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketMetricsRequest) ProtoMessage() {}

func (x *GetMarketMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMarketMetricsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{14}
}

type GetMarketMetricsResponse struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	TotalTransactions uint32                                 `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalVolume       float64                                `protobuf:"fixed64,2,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	TopProducts       []*GetMarketMetricsResponse_TopProduct `protobuf:"bytes,3,rep,name=top_products,json=topProducts,proto3" json:"top_products,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMarketMetricsResponse) Reset() {
	*x = GetMarketMetricsResponse{}
	mi := &file_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketMetricsResponse) ProtoMessage() {}

func (x *GetMarketMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMarketMetricsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{15}
}

func (x *GetMarketMetricsResponse) GetTotalTransactions() uint32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *GetMarketMetricsResponse) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *GetMarketMetricsResponse) GetTopProducts() []*GetMarketMetricsResponse_TopProduct {
	if x != nil {
		return x.TopProducts
	}
	return nil
}

type EnrichedHolding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiceGradeId  string                 `protobuf:"bytes,1,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	GradeName     string                 `protobuf:"bytes,3,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	RealizedPnl   float64                `protobuf:"fixed64,6,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	TodayPrice    float64                `protobuf:"fixed64,7,opt,name=today_price,json=todayPrice,proto3" json:"today_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedHolding) Reset() {
	*x = EnrichedHolding{}
	mi := &file_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedHolding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedHolding) ProtoMessage() {}

func (x *EnrichedHolding) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedHolding.ProtoReflect.Descriptor instead.
func (*EnrichedHolding) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{16}
}

func (x *EnrichedHolding) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *EnrichedHolding) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *EnrichedHolding) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *EnrichedHolding) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *EnrichedHolding) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *EnrichedHolding) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *EnrichedHolding) GetTodayPrice() float64 {
	if x != nil {
		return x.TodayPrice
	}
	return 0
}

type GetHoldingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingsRequest) Reset() {
	*x = GetHoldingsRequest{}
	mi := &file_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingsRequest) ProtoMessage() {}

func (x *GetHoldingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingsRequest.ProtoReflect.Descriptor instead.
func (*GetHoldingsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{17}
}

func (x *GetHoldingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHoldingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holdings      []*EnrichedHolding     `protobuf:"bytes,1,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingsResponse) Reset() {
	*x = GetHoldingsResponse{}
	mi := &file_market_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingsResponse) ProtoMessage() {}

func (x *GetHoldingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingsResponse.ProtoReflect.Descriptor instead.
func (*GetHoldingsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{18}
}

func (x *GetHoldingsResponse) GetHoldings() []*EnrichedHolding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

type RealizedPnLRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealizedPnLRow) Reset() {
	*x = RealizedPnLRow{}
	mi := &file_market_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealizedPnLRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealizedPnLRow) ProtoMessage() {}

func (x *RealizedPnLRow) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealizedPnLRow.ProtoReflect.Descriptor instead.
func (*RealizedPnLRow) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{19}
}

func (x *RealizedPnLRow) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RealizedPnLRow) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetRealizedPnLHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealizedPnLHistoryRequest) Reset() {
	*x = GetRealizedPnLHistoryRequest{}
	mi := &file_market_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealizedPnLHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealizedPnLHistoryRequest) ProtoMessage() {}

func (x *GetRealizedPnLHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealizedPnLHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRealizedPnLHistoryRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{20}
}

func (x *GetRealizedPnLHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRealizedPnLHistoryRequest) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetRealizedPnLHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*RealizedPnLRow      `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealizedPnLHistoryResponse) Reset() {
	*x = GetRealizedPnLHistoryResponse{}
	mi := &file_market_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealizedPnLHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealizedPnLHistoryResponse) ProtoMessage() {}

func (x *GetRealizedPnLHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealizedPnLHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetRealizedPnLHistoryResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{21}
}

func (x *GetRealizedPnLHistoryResponse) GetRows() []*RealizedPnLRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type TradeActivityRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // BUY or SELL
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeActivityRow) Reset() {
	*x = TradeActivityRow{}
	mi := &file_market_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeActivityRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeActivityRow) ProtoMessage() {}

func (x *TradeActivityRow) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeActivityRow.ProtoReflect.Descriptor instead.
func (*TradeActivityRow) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{22}
}

func (x *TradeActivityRow) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TradeActivityRow) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TradeActivityRow) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeActivityRow) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTradeActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeActivityRequest) Reset() {
	*x = GetTradeActivityRequest{}
	mi := &file_market_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeActivityRequest) ProtoMessage() {}

func (x *GetTradeActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeActivityRequest.ProtoReflect.Descriptor instead.
func (*GetTradeActivityRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{23}
}

func (x *GetTradeActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTradeActivityRequest) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetTradeActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TradeActivityRow    `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeActivityResponse) Reset() {
	*x = GetTradeActivityResponse{}
	mi := &file_market_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeActivityResponse) ProtoMessage() {}

func (x *GetTradeActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeActivityResponse.ProtoReflect.Descriptor instead.
func (*GetTradeActivityResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{24}
}

func (x *GetTradeActivityResponse) GetRows() []*TradeActivityRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GetTradeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeStatsRequest) Reset() {
	*x = GetTradeStatsRequest{}
	mi := &file_market_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeStatsRequest) ProtoMessage() {}

func (x *GetTradeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTradeStatsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{25}
}

func (x *GetTradeStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTradeStatsRequest) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetTradeStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TradesInPeriod     uint32                 `protobuf:"varint,1,opt,name=trades_in_period,json=tradesInPeriod,proto3" json:"trades_in_period,omitempty"`
	BuyVolumeInPeriod  float64                `protobuf:"fixed64,2,opt,name=buy_volume_in_period,json=buyVolumeInPeriod,proto3" json:"buy_volume_in_period,omitempty"`
	SellVolumeInPeriod float64                `protobuf:"fixed64,3,opt,name=sell_volume_in_period,json=sellVolumeInPeriod,proto3" json:"sell_volume_in_period,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTradeStatsResponse) Reset() {
	*x = GetTradeStatsResponse{}
	mi := &file_market_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeStatsResponse) ProtoMessage() {}

func (x *GetTradeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeStatsResponse.ProtoReflect.Descriptor instead.
func (*GetTradeStatsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{26}
}

func (x *GetTradeStatsResponse) GetTradesInPeriod() uint32 {
	if x != nil {
		return x.TradesInPeriod
	}
	return 0
}

func (x *GetTradeStatsResponse) GetBuyVolumeInPeriod() float64 {
	if x != nil {
		return x.BuyVolumeInPeriod
	}
	return 0
}

func (x *GetTradeStatsResponse) GetSellVolumeInPeriod() float64 {
	if x != nil {
		return x.SellVolumeInPeriod
	}
	return 0
}

type PriceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiceGradeId  string                 `protobuf:"bytes,1,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	GradeName     string                 `protobuf:"bytes,3,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	TodayPrice    float64                `protobuf:"fixed64,4,opt,name=today_price,json=todayPrice,proto3" json:"today_price,omitempty"`
	PreviousPrice float64                `protobuf:"fixed64,5,opt,name=previous_price,json=previousPrice,proto3" json:"previous_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceSnapshot) Reset() {
	*x = PriceSnapshot{}
	mi := &file_market_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceSnapshot) ProtoMessage() {}

func (x *PriceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceSnapshot.ProtoReflect.Descriptor instead.
func (*PriceSnapshot) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{27}
}

func (x *PriceSnapshot) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *PriceSnapshot) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PriceSnapshot) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *PriceSnapshot) GetTodayPrice() float64 {
	if x != nil {
		return x.TodayPrice
	}
	return 0
}

func (x *PriceSnapshot) GetPreviousPrice() float64 {
	if x != nil {
		return x.PreviousPrice
	}
	return 0
}

type GetPriceSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceSnapshotsRequest) Reset() {
	*x = GetPriceSnapshotsRequest{}
	mi := &file_market_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceSnapshotsRequest) ProtoMessage() {}

func (x *GetPriceSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*GetPriceSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{28}
}

func (x *GetPriceSnapshotsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPriceSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*PriceSnapshot       `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceSnapshotsResponse) Reset() {
	*x = GetPriceSnapshotsResponse{}
	mi := &file_market_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceSnapshotsResponse) ProtoMessage() {}

func (x *GetPriceSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*GetPriceSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{29}
}

func (x *GetPriceSnapshotsResponse) GetSnapshots() []*PriceSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type GetMarketMetricsResponse_TopProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	GradeName     string                 `protobuf:"bytes,2,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketMetricsResponse_TopProduct) Reset() {
	*x = GetMarketMetricsResponse_TopProduct{}
	mi := &file_market_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketMetricsResponse_TopProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketMetricsResponse_TopProduct) ProtoMessage() {}

func (x *GetMarketMetricsResponse_TopProduct) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketMetricsResponse_TopProduct.ProtoReflect.Descriptor instead.
func (*GetMarketMetricsResponse_TopProduct) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{15, 0}
}

func (x *GetMarketMetricsResponse_TopProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *GetMarketMetricsResponse_TopProduct) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *GetMarketMetricsResponse_TopProduct) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x02pb\"\xe0\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x03 \x01(\tR\fspiceGradeId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"trade_date\x18\a \x01(\tR\ttradeDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xae\x02\n" +
	"\fPositionView\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x1b\n" +
	"\ttotal_qty\x18\x03 \x01(\x01R\btotalQty\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12\x19\n" +
	"\bavg_cost\x18\x05 \x01(\x01R\aavgCost\x12\x1f\n" +
	"\vtoday_price\x18\x06 \x01(\x01R\n" +
	"todayPrice\x12!\n" +
	"\frealized_pnl\x18\a \x01(\x01R\vrealizedPnl\x12%\n" +
	"\x0eunrealized_pnl\x18\b \x01(\x01R\runrealizedPnl\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x9c\x01\n" +
	"\n" +
	"BuyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x05 \x01(\tR\ttradeDate\"@\n" +
	"\vBuyResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\"\x9d\x01\n" +
	"\vSellRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x05 \x01(\tR\ttradeDate\"A\n" +
	"\fSellResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\"X\n" +
	"\x17GetGradePositionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\"H\n" +
	"\x18GetGradePositionResponse\x12,\n" +
	"\bposition\x18\x01 \x01(\v2\x10.pb.PositionViewR\bposition\".\n" +
	"\x13GetPositionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x14GetPositionsResponse\x12.\n" +
	"\tpositions\x18\x01 \x03(\v2\x10.pb.PositionViewR\tpositions\"\x85\x01\n" +
	"\x1cListGradeTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x04 \x01(\rR\x04take\"T\n" +
	"\x1dListGradeTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"Z\n" +
	"\x17ListTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x03 \x01(\rR\x04take\"O\n" +
	"\x18ListTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"\x19\n" +
	"\x17GetMarketMetricsRequest\"\xa0\x02\n" +
	"\x18GetMarketMetricsResponse\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\rR\x11totalTransactions\x12!\n" +
	"\ftotal_volume\x18\x02 \x01(\x01R\vtotalVolume\x12J\n" +
	"\ftop_products\x18\x03 \x03(\v2'.pb.GetMarketMetricsResponse.TopProductR\vtopProducts\x1af\n" +
	"\n" +
	"TopProduct\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x02 \x01(\tR\tgradeName\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\"\xf8\x01\n" +
	"\x0fEnrichedHolding\x12$\n" +
	"\x0espice_grade_id\x18\x01 \x01(\tR\fspiceGradeId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x03 \x01(\tR\tgradeName\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x01R\ttotalCost\x12!\n" +
	"\frealized_pnl\x18\x06 \x01(\x01R\vrealizedPnl\x12\x1f\n" +
	"\vtoday_price\x18\a \x01(\x01R\n" +
	"todayPrice\"-\n" +
	"\x12GetHoldingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x13GetHoldingsResponse\x12/\n" +
	"\bholdings\x18\x01 \x03(\v2\x13.pb.EnrichedHoldingR\bholdings\"<\n" +
	"\x0eRealizedPnLRow\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"K\n" +
	"\x1cGetRealizedPnLHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\"G\n" +
	"\x1dGetRealizedPnLHistoryResponse\x12&\n" +
	"\x04rows\x18\x01 \x03(\v2\x12.pb.RealizedPnLRowR\x04rows\"l\n" +
	"\x10TradeActivityRow\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\"F\n" +
	"\x17GetTradeActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\"D\n" +
	"\x18GetTradeActivityResponse\x12(\n" +
	"\x04rows\x18\x01 \x03(\v2\x14.pb.TradeActivityRowR\x04rows\"C\n" +
	"\x14GetTradeStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\"\xa5\x01\n" +
	"\x15GetTradeStatsResponse\x12(\n" +
	"\x10trades_in_period\x18\x01 \x01(\rR\x0etradesInPeriod\x12/\n" +
	"\x14buy_volume_in_period\x18\x02 \x01(\x01R\x11buyVolumeInPeriod\x121\n" +
	"\x15sell_volume_in_period\x18\x03 \x01(\x01R\x12sellVolumeInPeriod\"\xbf\x01\n" +
	"\rPriceSnapshot\x12$\n" +
	"\x0espice_grade_id\x18\x01 \x01(\tR\fspiceGradeId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x03 \x01(\tR\tgradeName\x12\x1f\n" +
	"\vtoday_price\x18\x04 \x01(\x01R\n" +
	"todayPrice\x12%\n" +
	"\x0eprevious_price\x18\x05 \x01(\x01R\rpreviousPrice\"3\n" +
	"\x18GetPriceSnapshotsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x19GetPriceSnapshotsResponse\x12/\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x11.pb.PriceSnapshotR\tsnapshots2\xf5\x06\n" +
	"\rMarketService\x12&\n" +
	"\x03Buy\x12\x0e.pb.BuyRequest\x1a\x0f.pb.BuyResponse\x12)\n" +
	"\x04Sell\x12\x0f.pb.SellRequest\x1a\x10.pb.SellResponse\x12M\n" +
	"\x10GetGradePosition\x12\x1b.pb.GetGradePositionRequest\x1a\x1c.pb.GetGradePositionResponse\x12A\n" +
	"\fGetPositions\x12\x17.pb.GetPositionsRequest\x1a\x18.pb.GetPositionsResponse\x12\\\n" +
	"\x15ListGradeTransactions\x12 .pb.ListGradeTransactionsRequest\x1a!.pb.ListGradeTransactionsResponse\x12M\n" +
	"\x10ListTransactions\x12\x1b.pb.ListTransactionsRequest\x1a\x1c.pb.ListTransactionsResponse\x12M\n" +
	"\x10GetMarketMetrics\x12\x1b.pb.GetMarketMetricsRequest\x1a\x1c.pb.GetMarketMetricsResponse\x12>\n" +
	"\vGetHoldings\x12\x16.pb.GetHoldingsRequest\x1a\x17.pb.GetHoldingsResponse\x12\\\n" +
	"\x15GetRealizedPnLHistory\x12 .pb.GetRealizedPnLHistoryRequest\x1a!.pb.GetRealizedPnLHistoryResponse\x12M\n" +
	"\x10GetTradeActivity\x12\x1b.pb.GetTradeActivityRequest\x1a\x1c.pb.GetTradeActivityResponse\x12D\n" +
	"\rGetTradeStats\x12\x18.pb.GetTradeStatsRequest\x1a\x19.pb.GetTradeStatsResponse\x12P\n" +
	"\x11GetPriceSnapshots\x12\x1c.pb.GetPriceSnapshotsRequest\x1a\x1d.pb.GetPriceSnapshotsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_market_proto_goTypes = []any{
	(*Transaction)(nil),                         // 0: pb.Transaction
	(*PositionView)(nil),                        // 1: pb.PositionView
	(*BuyRequest)(nil),                          // 2: pb.BuyRequest
	(*BuyResponse)(nil),                         // 3: pb.BuyResponse
	(*SellRequest)(nil),                         // 4: pb.SellRequest
	(*SellResponse)(nil),                        // 5: pb.SellResponse
	(*GetGradePositionRequest)(nil),             // 6: pb.GetGradePositionRequest
	(*GetGradePositionResponse)(nil),            // 7: pb.GetGradePositionResponse
	(*GetPositionsRequest)(nil),                 // 8: pb.GetPositionsRequest
	(*GetPositionsResponse)(nil),                // 9: pb.GetPositionsResponse
	(*ListGradeTransactionsRequest)(nil),        // 10: pb.ListGradeTransactionsRequest
	(*ListGradeTransactionsResponse)(nil),       // 11: pb.ListGradeTransactionsResponse
	(*ListTransactionsRequest)(nil),             // 12: pb.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),            // 13: pb.ListTransactionsResponse
	(*GetMarketMetricsRequest)(nil),             // 14: pb.GetMarketMetricsRequest
	(*GetMarketMetricsResponse)(nil),            // 15: pb.GetMarketMetricsResponse
	(*EnrichedHolding)(nil),                     // 16: pb.EnrichedHolding
	(*GetHoldingsRequest)(nil),                  // 17: pb.GetHoldingsRequest
	(*GetHoldingsResponse)(nil),                 // 18: pb.GetHoldingsResponse
	(*RealizedPnLRow)(nil),                      // 19: pb.RealizedPnLRow
	(*GetRealizedPnLHistoryRequest)(nil),        // 20: pb.GetRealizedPnLHistoryRequest
	(*GetRealizedPnLHistoryResponse)(nil),       // 21: pb.GetRealizedPnLHistoryResponse
	(*TradeActivityRow)(nil),                    // 22: pb.TradeActivityRow
	(*GetTradeActivityRequest)(nil),             // 23: pb.GetTradeActivityRequest
	(*GetTradeActivityResponse)(nil),            // 24: pb.GetTradeActivityResponse
	(*GetTradeStatsRequest)(nil),                // 25: pb.GetTradeStatsRequest
	(*GetTradeStatsResponse)(nil),               // 26: pb.GetTradeStatsResponse
	(*PriceSnapshot)(nil),                       // 27: pb.PriceSnapshot
	(*GetPriceSnapshotsRequest)(nil),            // 28: pb.GetPriceSnapshotsRequest
	(*GetPriceSnapshotsResponse)(nil),           // 29: pb.GetPriceSnapshotsResponse
	(*GetMarketMetricsResponse_TopProduct)(nil), // 30: pb.GetMarketMetricsResponse.TopProduct
}
var file_market_proto_depIdxs = []int32{
	0,  // 0: pb.BuyResponse.transaction:type_name -> pb.Transaction
	0,  // 1: pb.SellResponse.transaction:type_name -> pb.Transaction
	1,  // 2: pb.GetGradePositionResponse.position:type_name -> pb.PositionView
	1,  // 3: pb.GetPositionsResponse.positions:type_name -> pb.PositionView
	0,  // 4: pb.ListGradeTransactionsResponse.transactions:type_name -> pb.Transaction
	0,  // 5: pb.ListTransactionsResponse.transactions:type_name -> pb.Transaction
	30, // 6: pb.GetMarketMetricsResponse.top_products:type_name -> pb.GetMarketMetricsResponse.TopProduct
	16, // 7: pb.GetHoldingsResponse.holdings:type_name -> pb.EnrichedHolding
	19, // 8: pb.GetRealizedPnLHistoryResponse.rows:type_name -> pb.RealizedPnLRow
	22, // 9: pb.GetTradeActivityResponse.rows:type_name -> pb.TradeActivityRow
	27, // 10: pb.GetPriceSnapshotsResponse.snapshots:type_name -> pb.PriceSnapshot
	2,  // 11: pb.MarketService.Buy:input_type -> pb.BuyRequest
	4,  // 12: pb.MarketService.Sell:input_type -> pb.SellRequest
	6,  // 13: pb.MarketService.GetGradePosition:input_type -> pb.GetGradePositionRequest
	8,  // 14: pb.MarketService.GetPositions:input_type -> pb.GetPositionsRequest
	10, // 15: pb.MarketService.ListGradeTransactions:input_type -> pb.ListGradeTransactionsRequest
	12, // 16: pb.MarketService.ListTransactions:input_type -> pb.ListTransactionsRequest
	14, // 17: pb.MarketService.GetMarketMetrics:input_type -> pb.GetMarketMetricsRequest
	17, // 18: pb.MarketService.GetHoldings:input_type -> pb.GetHoldingsRequest
	20, // 19: pb.MarketService.GetRealizedPnLHistory:input_type -> pb.GetRealizedPnLHistoryRequest
	23, // 20: pb.MarketService.GetTradeActivity:input_type -> pb.GetTradeActivityRequest
	25, // 21: pb.MarketService.GetTradeStats:input_type -> pb.GetTradeStatsRequest
	28, // 22: pb.MarketService.GetPriceSnapshots:input_type -> pb.GetPriceSnapshotsRequest
	3,  // 23: pb.MarketService.Buy:output_type -> pb.BuyResponse
	5,  // 24: pb.MarketService.Sell:output_type -> pb.SellResponse
	7,  // 25: pb.MarketService.GetGradePosition:output_type -> pb.GetGradePositionResponse
	9,  // 26: pb.MarketService.GetPositions:output_type -> pb.GetPositionsResponse
	11, // 27: pb.MarketService.ListGradeTransactions:output_type -> pb.ListGradeTransactionsResponse
	13, // 28: pb.MarketService.ListTransactions:output_type -> pb.ListTransactionsResponse
	15, // 29: pb.MarketService.GetMarketMetrics:output_type -> pb.GetMarketMetricsResponse
	18, // 30: pb.MarketService.GetHoldings:output_type -> pb.GetHoldingsResponse
	21, // 31: pb.MarketService.GetRealizedPnLHistory:output_type -> pb.GetRealizedPnLHistoryResponse
	24, // 32: pb.MarketService.GetTradeActivity:output_type -> pb.GetTradeActivityResponse
	26, // 33: pb.MarketService.GetTradeStats:output_type -> pb.GetTradeStatsResponse
	29, // 34: pb.MarketService.GetPriceSnapshots:output_type -> pb.GetPriceSnapshotsResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
