// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateDailyPriceInput struct {
	ID        string  `json:"id"`
	ProductID string  `json:"productId"`
	GradeID   string  `json:"gradeId"`
	Price     float64 `json:"price"`
	Date      string  `json:"date"`
	Time      string  `json:"time"`
}

type CreateGradeInput struct {
	ID          string  `json:"id"`
	ProductID   string  `json:"productId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type CreateProductInput struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Category    string  `json:"category"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type DailyPrice struct {
	ID        string  `json:"id"`
	ProductID string  `json:"productId"`
	GradeID   string  `json:"gradeId"`
	Price     float64 `json:"price"`
	Date      string  `json:"date"`
	Time      string  `json:"time"`
}

type Mutation struct {
}

type Query struct {
}
