// protoc --go_out=./pb --go-grpc_out=./pb control.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Usertype      string                 `protobuf:"bytes,3,opt,name=usertype,proto3" json:"usertype,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetUsertype() string {
	if x != nil {
		return x.Usertype
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type MerchantDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Pincode       string                 `protobuf:"bytes,7,opt,name=pincode,proto3" json:"pincode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantDetails) Reset() {
	*x = MerchantDetails{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantDetails) ProtoMessage() {}

func (x *MerchantDetails) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantDetails.ProtoReflect.Descriptor instead.
func (*MerchantDetails) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantDetails) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MerchantDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MerchantDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MerchantDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *MerchantDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MerchantDetails) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Grade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grade) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Grade) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Grade) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Grade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GradeWithPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeWithPrice) Reset() {
	*x = GradeWithPrice{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeWithPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeWithPrice) ProtoMessage() {}

func (x *GradeWithPrice) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeWithPrice.ProtoReflect.Descriptor instead.
func (*GradeWithPrice) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *GradeWithPrice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GradeWithPrice) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GradeWithPrice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GradeWithPrice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GradeWithPrice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GradeWithPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProductWithGrades struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Grades        []*GradeWithPrice      `protobuf:"bytes,6,rep,name=grades,proto3" json:"grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductWithGrades) Reset() {
	*x = ProductWithGrades{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductWithGrades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductWithGrades) ProtoMessage() {}

func (x *ProductWithGrades) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductWithGrades.ProtoReflect.Descriptor instead.
func (*ProductWithGrades) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *ProductWithGrades) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductWithGrades) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductWithGrades) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductWithGrades) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductWithGrades) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductWithGrades) GetGrades() []*GradeWithPrice {
	if x != nil {
		return x.Grades
	}
	return nil
}

type DailyPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	GradeId       string                 `protobuf:"bytes,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Time          string                 `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"` // HH:MM:SS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyPrice) Reset() {
	*x = DailyPrice{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPrice) ProtoMessage() {}

func (x *DailyPrice) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPrice.ProtoReflect.Descriptor instead.
func (*DailyPrice) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *DailyPrice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DailyPrice) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DailyPrice) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *DailyPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DailyPrice) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyPrice) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type CheckEmailExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailExistsRequest) Reset() {
	*x = CheckEmailExistsRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailExistsRequest) ProtoMessage() {}

func (x *CheckEmailExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckEmailExistsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *CheckEmailExistsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckEmailExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailExistsResponse) Reset() {
	*x = CheckEmailExistsResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailExistsResponse) ProtoMessage() {}

func (x *CheckEmailExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckEmailExistsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *CheckEmailExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CreateOrUpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Usertype      string                 `protobuf:"bytes,3,opt,name=usertype,proto3" json:"usertype,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateAccountRequest) Reset() {
	*x = CreateOrUpdateAccountRequest{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateAccountRequest) ProtoMessage() {}

func (x *CreateOrUpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrUpdateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrUpdateAccountRequest) GetUsertype() string {
	if x != nil {
		return x.Usertype
	}
	return ""
}

func (x *CreateOrUpdateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOrUpdateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateOrUpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateAccountResponse) Reset() {
	*x = CreateOrUpdateAccountResponse{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateAccountResponse) ProtoMessage() {}

func (x *CreateOrUpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrUpdateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIDRequest) Reset() {
	*x = GetAccountByIDRequest{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIDRequest) ProtoMessage() {}

func (x *GetAccountByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIDRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *GetAccountByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIDResponse) Reset() {
	*x = GetAccountByIDResponse{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIDResponse) ProtoMessage() {}

func (x *GetAccountByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByIDResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *GetAccountByIDResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint32                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *ListAccountsRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListAccountsRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *LoginResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *RefreshTokenResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateOrUpdateMerchantDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Pincode       string                 `protobuf:"bytes,7,opt,name=pincode,proto3" json:"pincode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateMerchantDetailsRequest) Reset() {
	*x = CreateOrUpdateMerchantDetailsRequest{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateMerchantDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateMerchantDetailsRequest) ProtoMessage() {}

func (x *CreateOrUpdateMerchantDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateMerchantDetailsRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateMerchantDetailsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateOrUpdateMerchantDetailsRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

type CreateOrUpdateMerchantInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Pincode       string                 `protobuf:"bytes,6,opt,name=pincode,proto3" json:"pincode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateMerchantInfoRequest) Reset() {
	*x = CreateOrUpdateMerchantInfoRequest{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateMerchantInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateMerchantInfoRequest) ProtoMessage() {}

func (x *CreateOrUpdateMerchantInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateMerchantInfoRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateMerchantInfoRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

func (x *CreateOrUpdateMerchantInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateMerchantInfoRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateOrUpdateMerchantInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrUpdateMerchantInfoRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateOrUpdateMerchantInfoRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateOrUpdateMerchantInfoRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

type CreateOrUpdateMerchantDetailsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantDetails *MerchantDetails       `protobuf:"bytes,1,opt,name=merchant_details,json=merchantDetails,proto3" json:"merchant_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrUpdateMerchantDetailsResponse) Reset() {
	*x = CreateOrUpdateMerchantDetailsResponse{}
	mi := &file_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateMerchantDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateMerchantDetailsResponse) ProtoMessage() {}

func (x *CreateOrUpdateMerchantDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateMerchantDetailsResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateMerchantDetailsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{23}
}

func (x *CreateOrUpdateMerchantDetailsResponse) GetMerchantDetails() *MerchantDetails {
	if x != nil {
		return x.MerchantDetails
	}
	return nil
}

type GetMerchantDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantDetailsRequest) Reset() {
	*x = GetMerchantDetailsRequest{}
	mi := &file_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantDetailsRequest) ProtoMessage() {}

func (x *GetMerchantDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantDetailsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{24}
}

func (x *GetMerchantDetailsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetMerchantDetailsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantDetails *MerchantDetails       `protobuf:"bytes,1,opt,name=merchant_details,json=merchantDetails,proto3" json:"merchant_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMerchantDetailsResponse) Reset() {
	*x = GetMerchantDetailsResponse{}
	mi := &file_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantDetailsResponse) ProtoMessage() {}

func (x *GetMerchantDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantDetailsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{25}
}

func (x *GetMerchantDetailsResponse) GetMerchantDetails() *MerchantDetails {
	if x != nil {
		return x.MerchantDetails
	}
	return nil
}

// Products
type CreateOrUpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateProductRequest) Reset() {
	*x = CreateOrUpdateProductRequest{}
	mi := &file_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateProductRequest) ProtoMessage() {}

func (x *CreateOrUpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{26}
}

func (x *CreateOrUpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrUpdateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateOrUpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrUpdateProductRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOrUpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateProductResponse) Reset() {
	*x = CreateOrUpdateProductResponse{}
	mi := &file_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateProductResponse) ProtoMessage() {}

func (x *CreateOrUpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{27}
}

func (x *CreateOrUpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint32                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{28}
}

func (x *ListProductsRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListProductsRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{29}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Grades
type CreateOrUpdateGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateGradeRequest) Reset() {
	*x = CreateOrUpdateGradeRequest{}
	mi := &file_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateGradeRequest) ProtoMessage() {}

func (x *CreateOrUpdateGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateGradeRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateGradeRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{30}
}

func (x *CreateOrUpdateGradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateGradeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrUpdateGradeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrUpdateGradeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrUpdateGradeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOrUpdateGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateGradeResponse) Reset() {
	*x = CreateOrUpdateGradeResponse{}
	mi := &file_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateGradeResponse) ProtoMessage() {}

func (x *CreateOrUpdateGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateGradeResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateGradeResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{31}
}

func (x *CreateOrUpdateGradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type ListGradesByProductIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Skip          uint32                 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradesByProductIdRequest) Reset() {
	*x = ListGradesByProductIdRequest{}
	mi := &file_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradesByProductIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesByProductIdRequest) ProtoMessage() {}

func (x *ListGradesByProductIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesByProductIdRequest.ProtoReflect.Descriptor instead.
func (*ListGradesByProductIdRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{32}
}

func (x *ListGradesByProductIdRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListGradesByProductIdRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListGradesByProductIdRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListGradesByProductIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*Grade               `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradesByProductIdResponse) Reset() {
	*x = ListGradesByProductIdResponse{}
	mi := &file_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradesByProductIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesByProductIdResponse) ProtoMessage() {}

func (x *ListGradesByProductIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesByProductIdResponse.ProtoReflect.Descriptor instead.
func (*ListGradesByProductIdResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{33}
}

func (x *ListGradesByProductIdResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

// Daily Prices
type CreateOrUpdateDailyPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	GradeId       string                 `protobuf:"bytes,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateDailyPriceRequest) Reset() {
	*x = CreateOrUpdateDailyPriceRequest{}
	mi := &file_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateDailyPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateDailyPriceRequest) ProtoMessage() {}

func (x *CreateOrUpdateDailyPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateDailyPriceRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateDailyPriceRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{34}
}

func (x *CreateOrUpdateDailyPriceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateDailyPriceRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrUpdateDailyPriceRequest) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *CreateOrUpdateDailyPriceRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrUpdateDailyPriceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateOrUpdateDailyPriceRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type CreateOrUpdateDailyPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyPrice    *DailyPrice            `protobuf:"bytes,1,opt,name=daily_price,json=dailyPrice,proto3" json:"daily_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateDailyPriceResponse) Reset() {
	*x = CreateOrUpdateDailyPriceResponse{}
	mi := &file_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateDailyPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateDailyPriceResponse) ProtoMessage() {}

func (x *CreateOrUpdateDailyPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateDailyPriceResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateDailyPriceResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{35}
}

func (x *CreateOrUpdateDailyPriceResponse) GetDailyPrice() *DailyPrice {
	if x != nil {
		return x.DailyPrice
	}
	return nil
}

type ListDailyPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Today         string                 `protobuf:"bytes,2,opt,name=today,proto3" json:"today,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDailyPricesRequest) Reset() {
	*x = ListDailyPricesRequest{}
	mi := &file_control_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDailyPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDailyPricesRequest) ProtoMessage() {}

func (x *ListDailyPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDailyPricesRequest.ProtoReflect.Descriptor instead.
func (*ListDailyPricesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{36}
}

func (x *ListDailyPricesRequest) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *ListDailyPricesRequest) GetToday() string {
	if x != nil {
		return x.Today
	}
	return ""
}

func (x *ListDailyPricesRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ListDailyPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyPrices   []*DailyPrice          `protobuf:"bytes,1,rep,name=daily_prices,json=dailyPrices,proto3" json:"daily_prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDailyPricesResponse) Reset() {
	*x = ListDailyPricesResponse{}
	mi := &file_control_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDailyPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDailyPricesResponse) ProtoMessage() {}

func (x *ListDailyPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDailyPricesResponse.ProtoReflect.Descriptor instead.
func (*ListDailyPricesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{37}
}

func (x *ListDailyPricesResponse) GetDailyPrices() []*DailyPrice {
	if x != nil {
		return x.DailyPrices
	}
	return nil
}

type GetTodaysPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodaysPriceRequest) Reset() {
	*x = GetTodaysPriceRequest{}
	mi := &file_control_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodaysPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodaysPriceRequest) ProtoMessage() {}

func (x *GetTodaysPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodaysPriceRequest.ProtoReflect.Descriptor instead.
func (*GetTodaysPriceRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{38}
}

func (x *GetTodaysPriceRequest) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *GetTodaysPriceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetTodaysPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyPrices   []*DailyPrice          `protobuf:"bytes,1,rep,name=daily_prices,json=dailyPrices,proto3" json:"daily_prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodaysPriceResponse) Reset() {
	*x = GetTodaysPriceResponse{}
	mi := &file_control_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodaysPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodaysPriceResponse) ProtoMessage() {}

func (x *GetTodaysPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodaysPriceResponse.ProtoReflect.Descriptor instead.
func (*GetTodaysPriceResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{39}
}

func (x *GetTodaysPriceResponse) GetDailyPrices() []*DailyPrice {
	if x != nil {
		return x.DailyPrices
	}
	return nil
}

type GetTodaysByProductIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodaysByProductIdRequest) Reset() {
	*x = GetTodaysByProductIdRequest{}
	mi := &file_control_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodaysByProductIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodaysByProductIdRequest) ProtoMessage() {}

func (x *GetTodaysByProductIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodaysByProductIdRequest.ProtoReflect.Descriptor instead.
func (*GetTodaysByProductIdRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{40}
}

func (x *GetTodaysByProductIdRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetTodaysByProductIdRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetTodaysByProductIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyPrices   []*DailyPrice          `protobuf:"bytes,1,rep,name=daily_prices,json=dailyPrices,proto3" json:"daily_prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodaysByProductIdResponse) Reset() {
	*x = GetTodaysByProductIdResponse{}
	mi := &file_control_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodaysByProductIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodaysByProductIdResponse) ProtoMessage() {}

func (x *GetTodaysByProductIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodaysByProductIdResponse.ProtoReflect.Descriptor instead.
func (*GetTodaysByProductIdResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{41}
}

func (x *GetTodaysByProductIdResponse) GetDailyPrices() []*DailyPrice {
	if x != nil {
		return x.DailyPrices
	}
	return nil
}

type GetProductsWithGradesAndPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsWithGradesAndPricesRequest) Reset() {
	*x = GetProductsWithGradesAndPricesRequest{}
	mi := &file_control_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsWithGradesAndPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsWithGradesAndPricesRequest) ProtoMessage() {}

func (x *GetProductsWithGradesAndPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsWithGradesAndPricesRequest.ProtoReflect.Descriptor instead.
func (*GetProductsWithGradesAndPricesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{42}
}

func (x *GetProductsWithGradesAndPricesRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetProductsWithGradesAndPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductWithGrades   `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsWithGradesAndPricesResponse) Reset() {
	*x = GetProductsWithGradesAndPricesResponse{}
	mi := &file_control_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsWithGradesAndPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsWithGradesAndPricesResponse) ProtoMessage() {}

func (x *GetProductsWithGradesAndPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsWithGradesAndPricesResponse.ProtoReflect.Descriptor instead.
func (*GetProductsWithGradesAndPricesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{43}
}

func (x *GetProductsWithGradesAndPricesResponse) GetProducts() []*ProductWithGrades {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetAccountInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountInfoRequest) Reset() {
	*x = GetAccountInfoRequest{}
	mi := &file_control_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountInfoRequest) ProtoMessage() {}

func (x *GetAccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{44}
}

type GetMerchantInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantInfoRequest) Reset() {
	*x = GetMerchantInfoRequest{}
	mi := &file_control_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantInfoRequest) ProtoMessage() {}

func (x *GetMerchantInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantInfoRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{45}
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x02pb\"{\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busertype\x18\x03 \x01(\tR\busertype\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\xc1\x01\n" +
	"\x0fMerchantDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\apincode\x18\a \x01(\tR\apincode\"\x83\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x84\x01\n" +
	"\x05Grade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xa3\x01\n" +
	"\x0eGradeWithPrice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"\xb9\x01\n" +
	"\x11ProductWithGrades\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x06grades\x18\x06 \x03(\v2\x12.pb.GradeWithPriceR\x06grades\"\x94\x01\n" +
	"\n" +
	"DailyPrice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x19\n" +
	"\bgrade_id\x18\x03 \x01(\tR\agradeId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x06 \x01(\tR\x04time\"/\n" +
	"\x17CheckEmailExistsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x18CheckEmailExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x90\x01\n" +
	"\x1cCreateOrUpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busertype\x18\x03 \x01(\tR\busertype\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"F\n" +
	"\x1dCreateOrUpdateAccountResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\"'\n" +
	"\x15GetAccountByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x16GetAccountByIDResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\"=\n" +
	"\x13ListAccountsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\rR\x04take\"?\n" +
	"\x14ListAccountsResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.pb.AccountR\baccounts\"]\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"~\n" +
	"\rLoginResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"O\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x85\x01\n" +
	"\x14RefreshTokenResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccount\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"\xd6\x01\n" +
	"$CreateOrUpdateMerchantDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\apincode\x18\a \x01(\tR\apincode\"\xb4\x01\n" +
	"!CreateOrUpdateMerchantInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\apincode\x18\x06 \x01(\tR\apincode\"g\n" +
	"%CreateOrUpdateMerchantDetailsResponse\x12>\n" +
	"\x10merchant_details\x18\x01 \x01(\v2\x13.pb.MerchantDetailsR\x0fmerchantDetails\":\n" +
	"\x19GetMerchantDetailsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\\\n" +
	"\x1aGetMerchantDetailsResponse\x12>\n" +
	"\x10merchant_details\x18\x01 \x01(\v2\x13.pb.MerchantDetailsR\x0fmerchantDetails\"\x98\x01\n" +
	"\x1cCreateOrUpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"F\n" +
	"\x1dCreateOrUpdateProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.pb.ProductR\aproduct\"=\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\rR\x04take\"?\n" +
	"\x14ListProductsResponse\x12'\n" +
	"\bproducts\x18\x01 \x03(\v2\v.pb.ProductR\bproducts\"\x99\x01\n" +
	"\x1aCreateOrUpdateGradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\">\n" +
	"\x1bCreateOrUpdateGradeResponse\x12\x1f\n" +
	"\x05grade\x18\x01 \x01(\v2\t.pb.GradeR\x05grade\"e\n" +
	"\x1cListGradesByProductIdRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x03 \x01(\rR\x04take\"B\n" +
	"\x1dListGradesByProductIdResponse\x12!\n" +
	"\x06grades\x18\x01 \x03(\v2\t.pb.GradeR\x06grades\"\xa9\x01\n" +
	"\x1fCreateOrUpdateDailyPriceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x19\n" +
	"\bgrade_id\x18\x03 \x01(\tR\agradeId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x06 \x01(\tR\x04time\"S\n" +
	" CreateOrUpdateDailyPriceResponse\x12/\n" +
	"\vdaily_price\x18\x01 \x01(\v2\x0e.pb.DailyPriceR\n" +
	"dailyPrice\"e\n" +
	"\x16ListDailyPricesRequest\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12\x14\n" +
	"\x05today\x18\x02 \x01(\tR\x05today\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\"L\n" +
	"\x17ListDailyPricesResponse\x121\n" +
	"\fdaily_prices\x18\x01 \x03(\v2\x0e.pb.DailyPriceR\vdailyPrices\"F\n" +
	"\x15GetTodaysPriceRequest\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"K\n" +
	"\x16GetTodaysPriceResponse\x121\n" +
	"\fdaily_prices\x18\x01 \x03(\v2\x0e.pb.DailyPriceR\vdailyPrices\"P\n" +
	"\x1bGetTodaysByProductIdRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"Q\n" +
	"\x1cGetTodaysByProductIdResponse\x121\n" +
	"\fdaily_prices\x18\x01 \x03(\v2\x0e.pb.DailyPriceR\vdailyPrices\";\n" +
	"%GetProductsWithGradesAndPricesRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"[\n" +
	"&GetProductsWithGradesAndPricesResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.pb.ProductWithGradesR\bproducts\"\x17\n" +
	"\x15GetAccountInfoRequest\"\x18\n" +
	"\x16GetMerchantInfoRequest2\xe5\r\n" +
	"\x0eControlService\x12M\n" +
	"\x10CheckEmailExists\x12\x1b.pb.CheckEmailExistsRequest\x1a\x1c.pb.CheckEmailExistsResponse\x12\\\n" +
	"\x15CreateOrUpdateAccount\x12 .pb.CreateOrUpdateAccountRequest\x1a!.pb.CreateOrUpdateAccountResponse\x12G\n" +
	"\x0eGetAccountByID\x12\x19.pb.GetAccountByIDRequest\x1a\x1a.pb.GetAccountByIDResponse\x12G\n" +
	"\x0eGetAccountInfo\x12\x19.pb.GetAccountInfoRequest\x1a\x1a.pb.GetAccountByIDResponse\x12A\n" +
	"\fListAccounts\x12\x17.pb.ListAccountsRequest\x1a\x18.pb.ListAccountsResponse\x12,\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\x12/\n" +
	"\x06Logout\x12\x11.pb.LogoutRequest\x1a\x12.pb.LogoutResponse\x12A\n" +
	"\fRefreshToken\x12\x17.pb.RefreshTokenRequest\x1a\x18.pb.RefreshTokenResponse\x12t\n" +
	"\x1dCreateOrUpdateMerchantDetails\x12(.pb.CreateOrUpdateMerchantDetailsRequest\x1a).pb.CreateOrUpdateMerchantDetailsResponse\x12S\n" +
	"\x12GetMerchantDetails\x12\x1d.pb.GetMerchantDetailsRequest\x1a\x1e.pb.GetMerchantDetailsResponse\x12M\n" +
	"\x0fGetMerchantInfo\x12\x1a.pb.GetMerchantInfoRequest\x1a\x1e.pb.GetMerchantDetailsResponse\x12n\n" +
	"\x1aCreateOrUpdateMerchantInfo\x12%.pb.CreateOrUpdateMerchantInfoRequest\x1a).pb.CreateOrUpdateMerchantDetailsResponse\x12\\\n" +
	"\x15CreateOrUpdateProduct\x12 .pb.CreateOrUpdateProductRequest\x1a!.pb.CreateOrUpdateProductResponse\x12A\n" +
	"\fListProducts\x12\x17.pb.ListProductsRequest\x1a\x18.pb.ListProductsResponse\x12V\n" +
	"\x13CreateOrUpdateGrade\x12\x1e.pb.CreateOrUpdateGradeRequest\x1a\x1f.pb.CreateOrUpdateGradeResponse\x12\\\n" +
	"\x15ListGradesByProductId\x12 .pb.ListGradesByProductIdRequest\x1a!.pb.ListGradesByProductIdResponse\x12e\n" +
	"\x18CreateOrUpdateDailyPrice\x12#.pb.CreateOrUpdateDailyPriceRequest\x1a$.pb.CreateOrUpdateDailyPriceResponse\x12J\n" +
	"\x0fListDailyPrices\x12\x1a.pb.ListDailyPricesRequest\x1a\x1b.pb.ListDailyPricesResponse\x12G\n" +
	"\x0eGetTodaysPrice\x12\x19.pb.GetTodaysPriceRequest\x1a\x1a.pb.GetTodaysPriceResponse\x12Y\n" +
	"\x14GetTodaysByProductId\x12\x1f.pb.GetTodaysByProductIdRequest\x1a .pb.GetTodaysByProductIdResponse\x12w\n" +
	"\x1eGetProductsWithGradesAndPrices\x12).pb.GetProductsWithGradesAndPricesRequest\x1a*.pb.GetProductsWithGradesAndPricesResponseB7Z5github.com/Asif-Faizal/SpiceLedger-Backend/control/pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_control_proto_goTypes = []any{
	(*Account)(nil),                                // 0: pb.Account
	(*MerchantDetails)(nil),                        // 1: pb.MerchantDetails
	(*Product)(nil),                                // 2: pb.Product
	(*Grade)(nil),                                  // 3: pb.Grade
	(*GradeWithPrice)(nil),                         // 4: pb.GradeWithPrice
	(*ProductWithGrades)(nil),                      // 5: pb.ProductWithGrades
	(*DailyPrice)(nil),                             // 6: pb.DailyPrice
	(*CheckEmailExistsRequest)(nil),                // 7: pb.CheckEmailExistsRequest
	(*CheckEmailExistsResponse)(nil),               // 8: pb.CheckEmailExistsResponse
	(*CreateOrUpdateAccountRequest)(nil),           // 9: pb.CreateOrUpdateAccountRequest
	(*CreateOrUpdateAccountResponse)(nil),          // 10: pb.CreateOrUpdateAccountResponse
	(*GetAccountByIDRequest)(nil),                  // 11: pb.GetAccountByIDRequest
	(*GetAccountByIDResponse)(nil),                 // 12: pb.GetAccountByIDResponse
	(*ListAccountsRequest)(nil),                    // 13: pb.ListAccountsRequest
	(*ListAccountsResponse)(nil),                   // 14: pb.ListAccountsResponse
	(*LoginRequest)(nil),                           // 15: pb.LoginRequest
	(*LoginResponse)(nil),                          // 16: pb.LoginResponse
	(*LogoutRequest)(nil),                          // 17: pb.LogoutRequest
	(*LogoutResponse)(nil),                         // 18: pb.LogoutResponse
	(*RefreshTokenRequest)(nil),                    // 19: pb.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),                   // 20: pb.RefreshTokenResponse
	(*CreateOrUpdateMerchantDetailsRequest)(nil),   // 21: pb.CreateOrUpdateMerchantDetailsRequest
	(*CreateOrUpdateMerchantInfoRequest)(nil),      // 22: pb.CreateOrUpdateMerchantInfoRequest
	(*CreateOrUpdateMerchantDetailsResponse)(nil),  // 23: pb.CreateOrUpdateMerchantDetailsResponse
	(*GetMerchantDetailsRequest)(nil),              // 24: pb.GetMerchantDetailsRequest
	(*GetMerchantDetailsResponse)(nil),             // 25: pb.GetMerchantDetailsResponse
	(*CreateOrUpdateProductRequest)(nil),           // 26: pb.CreateOrUpdateProductRequest
	(*CreateOrUpdateProductResponse)(nil),          // 27: pb.CreateOrUpdateProductResponse
	(*ListProductsRequest)(nil),                    // 28: pb.ListProductsRequest
	(*ListProductsResponse)(nil),                   // 29: pb.ListProductsResponse
	(*CreateOrUpdateGradeRequest)(nil),             // 30: pb.CreateOrUpdateGradeRequest
	(*CreateOrUpdateGradeResponse)(nil),            // 31: pb.CreateOrUpdateGradeResponse
	(*ListGradesByProductIdRequest)(nil),           // 32: pb.ListGradesByProductIdRequest
	(*ListGradesByProductIdResponse)(nil),          // 33: pb.ListGradesByProductIdResponse
	(*CreateOrUpdateDailyPriceRequest)(nil),        // 34: pb.CreateOrUpdateDailyPriceRequest
	(*CreateOrUpdateDailyPriceResponse)(nil),       // 35: pb.CreateOrUpdateDailyPriceResponse
	(*ListDailyPricesRequest)(nil),                 // 36: pb.ListDailyPricesRequest
	(*ListDailyPricesResponse)(nil),                // 37: pb.ListDailyPricesResponse
	(*GetTodaysPriceRequest)(nil),                  // 38: pb.GetTodaysPriceRequest
	(*GetTodaysPriceResponse)(nil),                 // 39: pb.GetTodaysPriceResponse
	(*GetTodaysByProductIdRequest)(nil),            // 40: pb.GetTodaysByProductIdRequest
	(*GetTodaysByProductIdResponse)(nil),           // 41: pb.GetTodaysByProductIdResponse
	(*GetProductsWithGradesAndPricesRequest)(nil),  // 42: pb.GetProductsWithGradesAndPricesRequest
	(*GetProductsWithGradesAndPricesResponse)(nil), // 43: pb.GetProductsWithGradesAndPricesResponse
	(*GetAccountInfoRequest)(nil),                  // 44: pb.GetAccountInfoRequest
	(*GetMerchantInfoRequest)(nil),                 // 45: pb.GetMerchantInfoRequest
}
var file_control_proto_depIdxs = []int32{
	4,  // 0: pb.ProductWithGrades.grades:type_name -> pb.GradeWithPrice
	0,  // 1: pb.CreateOrUpdateAccountResponse.account:type_name -> pb.Account
	0,  // 2: pb.GetAccountByIDResponse.account:type_name -> pb.Account
	0,  // 3: pb.ListAccountsResponse.accounts:type_name -> pb.Account
	0,  // 4: pb.LoginResponse.account:type_name -> pb.Account
	0,  // 5: pb.RefreshTokenResponse.account:type_name -> pb.Account
	1,  // 6: pb.CreateOrUpdateMerchantDetailsResponse.merchant_details:type_name -> pb.MerchantDetails
	1,  // 7: pb.GetMerchantDetailsResponse.merchant_details:type_name -> pb.MerchantDetails
	2,  // 8: pb.CreateOrUpdateProductResponse.product:type_name -> pb.Product
	2,  // 9: pb.ListProductsResponse.products:type_name -> pb.Product
	3,  // 10: pb.CreateOrUpdateGradeResponse.grade:type_name -> pb.Grade
	3,  // 11: pb.ListGradesByProductIdResponse.grades:type_name -> pb.Grade
	6,  // 12: pb.CreateOrUpdateDailyPriceResponse.daily_price:type_name -> pb.DailyPrice
	6,  // 13: pb.ListDailyPricesResponse.daily_prices:type_name -> pb.DailyPrice
	6,  // 14: pb.GetTodaysPriceResponse.daily_prices:type_name -> pb.DailyPrice
	6,  // 15: pb.GetTodaysByProductIdResponse.daily_prices:type_name -> pb.DailyPrice
	5,  // 16: pb.GetProductsWithGradesAndPricesResponse.products:type_name -> pb.ProductWithGrades
	7,  // 17: pb.ControlService.CheckEmailExists:input_type -> pb.CheckEmailExistsRequest
	9,  // 18: pb.ControlService.CreateOrUpdateAccount:input_type -> pb.CreateOrUpdateAccountRequest
	11, // 19: pb.ControlService.GetAccountByID:input_type -> pb.GetAccountByIDRequest
	44, // 20: pb.ControlService.GetAccountInfo:input_type -> pb.GetAccountInfoRequest
	13, // 21: pb.ControlService.ListAccounts:input_type -> pb.ListAccountsRequest
	15, // 22: pb.ControlService.Login:input_type -> pb.LoginRequest
	17, // 23: pb.ControlService.Logout:input_type -> pb.LogoutRequest
	19, // 24: pb.ControlService.RefreshToken:input_type -> pb.RefreshTokenRequest
	21, // 25: pb.ControlService.CreateOrUpdateMerchantDetails:input_type -> pb.CreateOrUpdateMerchantDetailsRequest
	24, // 26: pb.ControlService.GetMerchantDetails:input_type -> pb.GetMerchantDetailsRequest
	45, // 27: pb.ControlService.GetMerchantInfo:input_type -> pb.GetMerchantInfoRequest
	22, // 28: pb.ControlService.CreateOrUpdateMerchantInfo:input_type -> pb.CreateOrUpdateMerchantInfoRequest
	26, // 29: pb.ControlService.CreateOrUpdateProduct:input_type -> pb.CreateOrUpdateProductRequest
	28, // 30: pb.ControlService.ListProducts:input_type -> pb.ListProductsRequest
	30, // 31: pb.ControlService.CreateOrUpdateGrade:input_type -> pb.CreateOrUpdateGradeRequest
	32, // 32: pb.ControlService.ListGradesByProductId:input_type -> pb.ListGradesByProductIdRequest
	34, // 33: pb.ControlService.CreateOrUpdateDailyPrice:input_type -> pb.CreateOrUpdateDailyPriceRequest
	36, // 34: pb.ControlService.ListDailyPrices:input_type -> pb.ListDailyPricesRequest
	38, // 35: pb.ControlService.GetTodaysPrice:input_type -> pb.GetTodaysPriceRequest
	40, // 36: pb.ControlService.GetTodaysByProductId:input_type -> pb.GetTodaysByProductIdRequest
	42, // 37: pb.ControlService.GetProductsWithGradesAndPrices:input_type -> pb.GetProductsWithGradesAndPricesRequest
	8,  // 38: pb.ControlService.CheckEmailExists:output_type -> pb.CheckEmailExistsResponse
	10, // 39: pb.ControlService.CreateOrUpdateAccount:output_type -> pb.CreateOrUpdateAccountResponse
	12, // 40: pb.ControlService.GetAccountByID:output_type -> pb.GetAccountByIDResponse
	12, // 41: pb.ControlService.GetAccountInfo:output_type -> pb.GetAccountByIDResponse
	14, // 42: pb.ControlService.ListAccounts:output_type -> pb.ListAccountsResponse
	16, // 43: pb.ControlService.Login:output_type -> pb.LoginResponse
	18, // 44: pb.ControlService.Logout:output_type -> pb.LogoutResponse
	20, // 45: pb.ControlService.RefreshToken:output_type -> pb.RefreshTokenResponse
	23, // 46: pb.ControlService.CreateOrUpdateMerchantDetails:output_type -> pb.CreateOrUpdateMerchantDetailsResponse
	25, // 47: pb.ControlService.GetMerchantDetails:output_type -> pb.GetMerchantDetailsResponse
	25, // 48: pb.ControlService.GetMerchantInfo:output_type -> pb.GetMerchantDetailsResponse
	23, // 49: pb.ControlService.CreateOrUpdateMerchantInfo:output_type -> pb.CreateOrUpdateMerchantDetailsResponse
	27, // 50: pb.ControlService.CreateOrUpdateProduct:output_type -> pb.CreateOrUpdateProductResponse
	29, // 51: pb.ControlService.ListProducts:output_type -> pb.ListProductsResponse
	31, // 52: pb.ControlService.CreateOrUpdateGrade:output_type -> pb.CreateOrUpdateGradeResponse
	33, // 53: pb.ControlService.ListGradesByProductId:output_type -> pb.ListGradesByProductIdResponse
	35, // 54: pb.ControlService.CreateOrUpdateDailyPrice:output_type -> pb.CreateOrUpdateDailyPriceResponse
	37, // 55: pb.ControlService.ListDailyPrices:output_type -> pb.ListDailyPricesResponse
	39, // 56: pb.ControlService.GetTodaysPrice:output_type -> pb.GetTodaysPriceResponse
	41, // 57: pb.ControlService.GetTodaysByProductId:output_type -> pb.GetTodaysByProductIdResponse
	43, // 58: pb.ControlService.GetProductsWithGradesAndPrices:output_type -> pb.GetProductsWithGradesAndPricesResponse
	38, // [38:59] is the sub-list for method output_type
	17, // [17:38] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
