// protoc --go_out=./pb --go-grpc_out=./pb control.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: control.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_CheckEmailExists_FullMethodName              = "/pb.ControlService/CheckEmailExists"
	ControlService_CreateOrUpdateAccount_FullMethodName         = "/pb.ControlService/CreateOrUpdateAccount"
	ControlService_GetAccountByID_FullMethodName                = "/pb.ControlService/GetAccountByID"
	ControlService_GetAccountInfo_FullMethodName                = "/pb.ControlService/GetAccountInfo"
	ControlService_ListAccounts_FullMethodName                  = "/pb.ControlService/ListAccounts"
	ControlService_Login_FullMethodName                         = "/pb.ControlService/Login"
	ControlService_Logout_FullMethodName                        = "/pb.ControlService/Logout"
	ControlService_RefreshToken_FullMethodName                  = "/pb.ControlService/RefreshToken"
	ControlService_CreateOrUpdateMerchantDetails_FullMethodName = "/pb.ControlService/CreateOrUpdateMerchantDetails"
	ControlService_GetMerchantDetails_FullMethodName            = "/pb.ControlService/GetMerchantDetails"
	ControlService_CreateOrUpdateProduct_FullMethodName         = "/pb.ControlService/CreateOrUpdateProduct"
	ControlService_ListProducts_FullMethodName                  = "/pb.ControlService/ListProducts"
	ControlService_CreateOrUpdateGrade_FullMethodName           = "/pb.ControlService/CreateOrUpdateGrade"
	ControlService_ListGradesByProductId_FullMethodName         = "/pb.ControlService/ListGradesByProductId"
	ControlService_CreateOrUpdateDailyPrice_FullMethodName      = "/pb.ControlService/CreateOrUpdateDailyPrice"
	ControlService_ListDailyPrices_FullMethodName               = "/pb.ControlService/ListDailyPrices"
	ControlService_GetTodaysPrice_FullMethodName                = "/pb.ControlService/GetTodaysPrice"
	ControlService_GetTodaysByProductId_FullMethodName          = "/pb.ControlService/GetTodaysByProductId"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	CheckEmailExists(ctx context.Context, in *CheckEmailExistsRequest, opts ...grpc.CallOption) (*CheckEmailExistsResponse, error)
	CreateOrUpdateAccount(ctx context.Context, in *CreateOrUpdateAccountRequest, opts ...grpc.CallOption) (*CreateOrUpdateAccountResponse, error)
	GetAccountByID(ctx context.Context, in *GetAccountByIDRequest, opts ...grpc.CallOption) (*GetAccountByIDResponse, error)
	GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountByIDResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	CreateOrUpdateMerchantDetails(ctx context.Context, in *CreateOrUpdateMerchantDetailsRequest, opts ...grpc.CallOption) (*CreateOrUpdateMerchantDetailsResponse, error)
	GetMerchantDetails(ctx context.Context, in *GetMerchantDetailsRequest, opts ...grpc.CallOption) (*GetMerchantDetailsResponse, error)
	// Product Management
	CreateOrUpdateProduct(ctx context.Context, in *CreateOrUpdateProductRequest, opts ...grpc.CallOption) (*CreateOrUpdateProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// Grade Management
	CreateOrUpdateGrade(ctx context.Context, in *CreateOrUpdateGradeRequest, opts ...grpc.CallOption) (*CreateOrUpdateGradeResponse, error)
	ListGradesByProductId(ctx context.Context, in *ListGradesByProductIdRequest, opts ...grpc.CallOption) (*ListGradesByProductIdResponse, error)
	// Daily Price Management
	CreateOrUpdateDailyPrice(ctx context.Context, in *CreateOrUpdateDailyPriceRequest, opts ...grpc.CallOption) (*CreateOrUpdateDailyPriceResponse, error)
	ListDailyPrices(ctx context.Context, in *ListDailyPricesRequest, opts ...grpc.CallOption) (*ListDailyPricesResponse, error)
	GetTodaysPrice(ctx context.Context, in *GetTodaysPriceRequest, opts ...grpc.CallOption) (*GetTodaysPriceResponse, error)
	GetTodaysByProductId(ctx context.Context, in *GetTodaysByProductIdRequest, opts ...grpc.CallOption) (*GetTodaysByProductIdResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) CheckEmailExists(ctx context.Context, in *CheckEmailExistsRequest, opts ...grpc.CallOption) (*CheckEmailExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEmailExistsResponse)
	err := c.cc.Invoke(ctx, ControlService_CheckEmailExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateOrUpdateAccount(ctx context.Context, in *CreateOrUpdateAccountRequest, opts ...grpc.CallOption) (*CreateOrUpdateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateAccountResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateOrUpdateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetAccountByID(ctx context.Context, in *GetAccountByIDRequest, opts ...grpc.CallOption) (*GetAccountByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountByIDResponse)
	err := c.cc.Invoke(ctx, ControlService_GetAccountByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountByIDResponse)
	err := c.cc.Invoke(ctx, ControlService_GetAccountInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, ControlService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, ControlService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, ControlService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateOrUpdateMerchantDetails(ctx context.Context, in *CreateOrUpdateMerchantDetailsRequest, opts ...grpc.CallOption) (*CreateOrUpdateMerchantDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateMerchantDetailsResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateOrUpdateMerchantDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetMerchantDetails(ctx context.Context, in *GetMerchantDetailsRequest, opts ...grpc.CallOption) (*GetMerchantDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantDetailsResponse)
	err := c.cc.Invoke(ctx, ControlService_GetMerchantDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateOrUpdateProduct(ctx context.Context, in *CreateOrUpdateProductRequest, opts ...grpc.CallOption) (*CreateOrUpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateProductResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateOrUpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateOrUpdateGrade(ctx context.Context, in *CreateOrUpdateGradeRequest, opts ...grpc.CallOption) (*CreateOrUpdateGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateGradeResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateOrUpdateGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListGradesByProductId(ctx context.Context, in *ListGradesByProductIdRequest, opts ...grpc.CallOption) (*ListGradesByProductIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGradesByProductIdResponse)
	err := c.cc.Invoke(ctx, ControlService_ListGradesByProductId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateOrUpdateDailyPrice(ctx context.Context, in *CreateOrUpdateDailyPriceRequest, opts ...grpc.CallOption) (*CreateOrUpdateDailyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateDailyPriceResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateOrUpdateDailyPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListDailyPrices(ctx context.Context, in *ListDailyPricesRequest, opts ...grpc.CallOption) (*ListDailyPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDailyPricesResponse)
	err := c.cc.Invoke(ctx, ControlService_ListDailyPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetTodaysPrice(ctx context.Context, in *GetTodaysPriceRequest, opts ...grpc.CallOption) (*GetTodaysPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodaysPriceResponse)
	err := c.cc.Invoke(ctx, ControlService_GetTodaysPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetTodaysByProductId(ctx context.Context, in *GetTodaysByProductIdRequest, opts ...grpc.CallOption) (*GetTodaysByProductIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodaysByProductIdResponse)
	err := c.cc.Invoke(ctx, ControlService_GetTodaysByProductId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	CheckEmailExists(context.Context, *CheckEmailExistsRequest) (*CheckEmailExistsResponse, error)
	CreateOrUpdateAccount(context.Context, *CreateOrUpdateAccountRequest) (*CreateOrUpdateAccountResponse, error)
	GetAccountByID(context.Context, *GetAccountByIDRequest) (*GetAccountByIDResponse, error)
	GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountByIDResponse, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	CreateOrUpdateMerchantDetails(context.Context, *CreateOrUpdateMerchantDetailsRequest) (*CreateOrUpdateMerchantDetailsResponse, error)
	GetMerchantDetails(context.Context, *GetMerchantDetailsRequest) (*GetMerchantDetailsResponse, error)
	// Product Management
	CreateOrUpdateProduct(context.Context, *CreateOrUpdateProductRequest) (*CreateOrUpdateProductResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	// Grade Management
	CreateOrUpdateGrade(context.Context, *CreateOrUpdateGradeRequest) (*CreateOrUpdateGradeResponse, error)
	ListGradesByProductId(context.Context, *ListGradesByProductIdRequest) (*ListGradesByProductIdResponse, error)
	// Daily Price Management
	CreateOrUpdateDailyPrice(context.Context, *CreateOrUpdateDailyPriceRequest) (*CreateOrUpdateDailyPriceResponse, error)
	ListDailyPrices(context.Context, *ListDailyPricesRequest) (*ListDailyPricesResponse, error)
	GetTodaysPrice(context.Context, *GetTodaysPriceRequest) (*GetTodaysPriceResponse, error)
	GetTodaysByProductId(context.Context, *GetTodaysByProductIdRequest) (*GetTodaysByProductIdResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) CheckEmailExists(context.Context, *CheckEmailExistsRequest) (*CheckEmailExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEmailExists not implemented")
}
func (UnimplementedControlServiceServer) CreateOrUpdateAccount(context.Context, *CreateOrUpdateAccountRequest) (*CreateOrUpdateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateAccount not implemented")
}
func (UnimplementedControlServiceServer) GetAccountByID(context.Context, *GetAccountByIDRequest) (*GetAccountByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountByID not implemented")
}
func (UnimplementedControlServiceServer) GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountInfo not implemented")
}
func (UnimplementedControlServiceServer) ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedControlServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedControlServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedControlServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedControlServiceServer) CreateOrUpdateMerchantDetails(context.Context, *CreateOrUpdateMerchantDetailsRequest) (*CreateOrUpdateMerchantDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateMerchantDetails not implemented")
}
func (UnimplementedControlServiceServer) GetMerchantDetails(context.Context, *GetMerchantDetailsRequest) (*GetMerchantDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchantDetails not implemented")
}
func (UnimplementedControlServiceServer) CreateOrUpdateProduct(context.Context, *CreateOrUpdateProductRequest) (*CreateOrUpdateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateProduct not implemented")
}
func (UnimplementedControlServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedControlServiceServer) CreateOrUpdateGrade(context.Context, *CreateOrUpdateGradeRequest) (*CreateOrUpdateGradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateGrade not implemented")
}
func (UnimplementedControlServiceServer) ListGradesByProductId(context.Context, *ListGradesByProductIdRequest) (*ListGradesByProductIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGradesByProductId not implemented")
}
func (UnimplementedControlServiceServer) CreateOrUpdateDailyPrice(context.Context, *CreateOrUpdateDailyPriceRequest) (*CreateOrUpdateDailyPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateDailyPrice not implemented")
}
func (UnimplementedControlServiceServer) ListDailyPrices(context.Context, *ListDailyPricesRequest) (*ListDailyPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDailyPrices not implemented")
}
func (UnimplementedControlServiceServer) GetTodaysPrice(context.Context, *GetTodaysPriceRequest) (*GetTodaysPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTodaysPrice not implemented")
}
func (UnimplementedControlServiceServer) GetTodaysByProductId(context.Context, *GetTodaysByProductIdRequest) (*GetTodaysByProductIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTodaysByProductId not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_CheckEmailExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEmailExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CheckEmailExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CheckEmailExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CheckEmailExists(ctx, req.(*CheckEmailExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateOrUpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateOrUpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateOrUpdateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateOrUpdateAccount(ctx, req.(*CreateOrUpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetAccountByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetAccountByID(ctx, req.(*GetAccountByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetAccountInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetAccountInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateOrUpdateMerchantDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateMerchantDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateOrUpdateMerchantDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateOrUpdateMerchantDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateOrUpdateMerchantDetails(ctx, req.(*CreateOrUpdateMerchantDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetMerchantDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetMerchantDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetMerchantDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetMerchantDetails(ctx, req.(*GetMerchantDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateOrUpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateOrUpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateOrUpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateOrUpdateProduct(ctx, req.(*CreateOrUpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateOrUpdateGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateOrUpdateGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateOrUpdateGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateOrUpdateGrade(ctx, req.(*CreateOrUpdateGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListGradesByProductId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGradesByProductIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListGradesByProductId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListGradesByProductId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListGradesByProductId(ctx, req.(*ListGradesByProductIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateOrUpdateDailyPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateDailyPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateOrUpdateDailyPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateOrUpdateDailyPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateOrUpdateDailyPrice(ctx, req.(*CreateOrUpdateDailyPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListDailyPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDailyPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListDailyPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListDailyPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListDailyPrices(ctx, req.(*ListDailyPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetTodaysPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodaysPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetTodaysPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetTodaysPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetTodaysPrice(ctx, req.(*GetTodaysPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetTodaysByProductId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodaysByProductIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetTodaysByProductId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetTodaysByProductId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetTodaysByProductId(ctx, req.(*GetTodaysByProductIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckEmailExists",
			Handler:    _ControlService_CheckEmailExists_Handler,
		},
		{
			MethodName: "CreateOrUpdateAccount",
			Handler:    _ControlService_CreateOrUpdateAccount_Handler,
		},
		{
			MethodName: "GetAccountByID",
			Handler:    _ControlService_GetAccountByID_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _ControlService_GetAccountInfo_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _ControlService_ListAccounts_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ControlService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _ControlService_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _ControlService_RefreshToken_Handler,
		},
		{
			MethodName: "CreateOrUpdateMerchantDetails",
			Handler:    _ControlService_CreateOrUpdateMerchantDetails_Handler,
		},
		{
			MethodName: "GetMerchantDetails",
			Handler:    _ControlService_GetMerchantDetails_Handler,
		},
		{
			MethodName: "CreateOrUpdateProduct",
			Handler:    _ControlService_CreateOrUpdateProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ControlService_ListProducts_Handler,
		},
		{
			MethodName: "CreateOrUpdateGrade",
			Handler:    _ControlService_CreateOrUpdateGrade_Handler,
		},
		{
			MethodName: "ListGradesByProductId",
			Handler:    _ControlService_ListGradesByProductId_Handler,
		},
		{
			MethodName: "CreateOrUpdateDailyPrice",
			Handler:    _ControlService_CreateOrUpdateDailyPrice_Handler,
		},
		{
			MethodName: "ListDailyPrices",
			Handler:    _ControlService_ListDailyPrices_Handler,
		},
		{
			MethodName: "GetTodaysPrice",
			Handler:    _ControlService_GetTodaysPrice_Handler,
		},
		{
			MethodName: "GetTodaysByProductId",
			Handler:    _ControlService_GetTodaysByProductId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
