// protoc --go_out=./pb --go-grpc_out=./pb market.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: market.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,3,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	TradeDate     string                 `protobuf:"bytes,7,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"` // YYYY-MM-DD
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // YYYY-MM-DD HH:MM:SS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Transaction) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Transaction) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PositionView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	TotalQty      float64                `protobuf:"fixed64,3,opt,name=total_qty,json=totalQty,proto3" json:"total_qty,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	AvgCost       float64                `protobuf:"fixed64,5,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	TodayPrice    float64                `protobuf:"fixed64,6,opt,name=today_price,json=todayPrice,proto3" json:"today_price,omitempty"`
	RealizedPnl   float64                `protobuf:"fixed64,7,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	UnrealizedPnl float64                `protobuf:"fixed64,8,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionView) Reset() {
	*x = PositionView{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionView) ProtoMessage() {}

func (x *PositionView) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionView.ProtoReflect.Descriptor instead.
func (*PositionView) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *PositionView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PositionView) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *PositionView) GetTotalQty() float64 {
	if x != nil {
		return x.TotalQty
	}
	return 0
}

func (x *PositionView) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *PositionView) GetAvgCost() float64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *PositionView) GetTodayPrice() float64 {
	if x != nil {
		return x.TodayPrice
	}
	return 0
}

func (x *PositionView) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *PositionView) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *PositionView) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	TradeDate     string                 `protobuf:"bytes,5,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *BuyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BuyRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *BuyRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

type BuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *BuyResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	TradeDate     string                 `protobuf:"bytes,5,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *SellRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SellRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *SellRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SellRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

type SellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellResponse) Reset() {
	*x = SellResponse{}
	mi := &file_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellResponse) ProtoMessage() {}

func (x *SellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellResponse.ProtoReflect.Descriptor instead.
func (*SellResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

func (x *SellResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetGradePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradePositionRequest) Reset() {
	*x = GetGradePositionRequest{}
	mi := &file_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradePositionRequest) ProtoMessage() {}

func (x *GetGradePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradePositionRequest.ProtoReflect.Descriptor instead.
func (*GetGradePositionRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{6}
}

func (x *GetGradePositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGradePositionRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

type GetGradePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionView          `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradePositionResponse) Reset() {
	*x = GetGradePositionResponse{}
	mi := &file_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradePositionResponse) ProtoMessage() {}

func (x *GetGradePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradePositionResponse.ProtoReflect.Descriptor instead.
func (*GetGradePositionResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{7}
}

func (x *GetGradePositionResponse) GetPosition() *PositionView {
	if x != nil {
		return x.Position
	}
	return nil
}

type GetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsRequest) Reset() {
	*x = GetPositionsRequest{}
	mi := &file_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsRequest) ProtoMessage() {}

func (x *GetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{8}
}

func (x *GetPositionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*PositionView        `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsResponse) Reset() {
	*x = GetPositionsResponse{}
	mi := &file_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsResponse) ProtoMessage() {}

func (x *GetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{9}
}

func (x *GetPositionsResponse) GetPositions() []*PositionView {
	if x != nil {
		return x.Positions
	}
	return nil
}

type ListGradeTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,2,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	Skip          uint32                 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradeTransactionsRequest) Reset() {
	*x = ListGradeTransactionsRequest{}
	mi := &file_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradeTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradeTransactionsRequest) ProtoMessage() {}

func (x *ListGradeTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradeTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListGradeTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{10}
}

func (x *ListGradeTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListGradeTransactionsRequest) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *ListGradeTransactionsRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListGradeTransactionsRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListGradeTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradeTransactionsResponse) Reset() {
	*x = ListGradeTransactionsResponse{}
	mi := &file_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradeTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradeTransactionsResponse) ProtoMessage() {}

func (x *ListGradeTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradeTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListGradeTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{11}
}

func (x *ListGradeTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Skip          uint32                 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint32                 `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{12}
}

func (x *ListTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTransactionsRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListTransactionsRequest) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{13}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetMarketMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketMetricsRequest) Reset() {
	*x = GetMarketMetricsRequest{}
	mi := &file_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketMetricsRequest) ProtoMessage() {}

func (x *GetMarketMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMarketMetricsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{14}
}

type GetMarketMetricsResponse struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	TotalTransactions uint32                                 `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalVolume       float64                                `protobuf:"fixed64,2,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	TopProducts       []*GetMarketMetricsResponse_TopProduct `protobuf:"bytes,3,rep,name=top_products,json=topProducts,proto3" json:"top_products,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMarketMetricsResponse) Reset() {
	*x = GetMarketMetricsResponse{}
	mi := &file_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketMetricsResponse) ProtoMessage() {}

func (x *GetMarketMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMarketMetricsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{15}
}

func (x *GetMarketMetricsResponse) GetTotalTransactions() uint32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *GetMarketMetricsResponse) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *GetMarketMetricsResponse) GetTopProducts() []*GetMarketMetricsResponse_TopProduct {
	if x != nil {
		return x.TopProducts
	}
	return nil
}

type GetMerchantDashboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trend window in days for charts (default 7, max 90). Account identity comes from JWT only.
	Days          uint32 `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantDashboardRequest) Reset() {
	*x = GetMerchantDashboardRequest{}
	mi := &file_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantDashboardRequest) ProtoMessage() {}

func (x *GetMerchantDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantDashboardRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{16}
}

func (x *GetMerchantDashboardRequest) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type MerchantSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PortfolioValue     float64                `protobuf:"fixed64,1,opt,name=portfolio_value,json=portfolioValue,proto3" json:"portfolio_value,omitempty"`
	TotalCost          float64                `protobuf:"fixed64,2,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	TotalRealizedPnl   float64                `protobuf:"fixed64,3,opt,name=total_realized_pnl,json=totalRealizedPnl,proto3" json:"total_realized_pnl,omitempty"`
	TotalUnrealizedPnl float64                `protobuf:"fixed64,4,opt,name=total_unrealized_pnl,json=totalUnrealizedPnl,proto3" json:"total_unrealized_pnl,omitempty"`
	NetPnl             float64                `protobuf:"fixed64,5,opt,name=net_pnl,json=netPnl,proto3" json:"net_pnl,omitempty"`
	OpenPositions      uint32                 `protobuf:"varint,6,opt,name=open_positions,json=openPositions,proto3" json:"open_positions,omitempty"`
	TotalQuantityKg    float64                `protobuf:"fixed64,7,opt,name=total_quantity_kg,json=totalQuantityKg,proto3" json:"total_quantity_kg,omitempty"`
	TradesInPeriod     uint32                 `protobuf:"varint,8,opt,name=trades_in_period,json=tradesInPeriod,proto3" json:"trades_in_period,omitempty"`
	BuyVolumeInPeriod  float64                `protobuf:"fixed64,9,opt,name=buy_volume_in_period,json=buyVolumeInPeriod,proto3" json:"buy_volume_in_period,omitempty"`
	SellVolumeInPeriod float64                `protobuf:"fixed64,10,opt,name=sell_volume_in_period,json=sellVolumeInPeriod,proto3" json:"sell_volume_in_period,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MerchantSummary) Reset() {
	*x = MerchantSummary{}
	mi := &file_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantSummary) ProtoMessage() {}

func (x *MerchantSummary) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantSummary.ProtoReflect.Descriptor instead.
func (*MerchantSummary) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{17}
}

func (x *MerchantSummary) GetPortfolioValue() float64 {
	if x != nil {
		return x.PortfolioValue
	}
	return 0
}

func (x *MerchantSummary) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *MerchantSummary) GetTotalRealizedPnl() float64 {
	if x != nil {
		return x.TotalRealizedPnl
	}
	return 0
}

func (x *MerchantSummary) GetTotalUnrealizedPnl() float64 {
	if x != nil {
		return x.TotalUnrealizedPnl
	}
	return 0
}

func (x *MerchantSummary) GetNetPnl() float64 {
	if x != nil {
		return x.NetPnl
	}
	return 0
}

func (x *MerchantSummary) GetOpenPositions() uint32 {
	if x != nil {
		return x.OpenPositions
	}
	return 0
}

func (x *MerchantSummary) GetTotalQuantityKg() float64 {
	if x != nil {
		return x.TotalQuantityKg
	}
	return 0
}

func (x *MerchantSummary) GetTradesInPeriod() uint32 {
	if x != nil {
		return x.TradesInPeriod
	}
	return 0
}

func (x *MerchantSummary) GetBuyVolumeInPeriod() float64 {
	if x != nil {
		return x.BuyVolumeInPeriod
	}
	return 0
}

func (x *MerchantSummary) GetSellVolumeInPeriod() float64 {
	if x != nil {
		return x.SellVolumeInPeriod
	}
	return 0
}

type MerchantHolding struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SpiceGradeId         string                 `protobuf:"bytes,1,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	ProductName          string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	GradeName            string                 `protobuf:"bytes,3,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	Quantity             float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AvgCost              float64                `protobuf:"fixed64,5,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	TodayPrice           float64                `protobuf:"fixed64,6,opt,name=today_price,json=todayPrice,proto3" json:"today_price,omitempty"`
	MarketValue          float64                `protobuf:"fixed64,7,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	CostBasis            float64                `protobuf:"fixed64,8,opt,name=cost_basis,json=costBasis,proto3" json:"cost_basis,omitempty"`
	UnrealizedPnl        float64                `protobuf:"fixed64,9,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	UnrealizedPnlPercent float64                `protobuf:"fixed64,10,opt,name=unrealized_pnl_percent,json=unrealizedPnlPercent,proto3" json:"unrealized_pnl_percent,omitempty"`
	RealizedPnl          float64                `protobuf:"fixed64,11,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	WeightPercent        float64                `protobuf:"fixed64,12,opt,name=weight_percent,json=weightPercent,proto3" json:"weight_percent,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MerchantHolding) Reset() {
	*x = MerchantHolding{}
	mi := &file_market_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantHolding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantHolding) ProtoMessage() {}

func (x *MerchantHolding) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantHolding.ProtoReflect.Descriptor instead.
func (*MerchantHolding) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{18}
}

func (x *MerchantHolding) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *MerchantHolding) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *MerchantHolding) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *MerchantHolding) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MerchantHolding) GetAvgCost() float64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *MerchantHolding) GetTodayPrice() float64 {
	if x != nil {
		return x.TodayPrice
	}
	return 0
}

func (x *MerchantHolding) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *MerchantHolding) GetCostBasis() float64 {
	if x != nil {
		return x.CostBasis
	}
	return 0
}

func (x *MerchantHolding) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *MerchantHolding) GetUnrealizedPnlPercent() float64 {
	if x != nil {
		return x.UnrealizedPnlPercent
	}
	return 0
}

func (x *MerchantHolding) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *MerchantHolding) GetWeightPercent() float64 {
	if x != nil {
		return x.WeightPercent
	}
	return 0
}

type PortfolioSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioSlice) Reset() {
	*x = PortfolioSlice{}
	mi := &file_market_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioSlice) ProtoMessage() {}

func (x *PortfolioSlice) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioSlice.ProtoReflect.Descriptor instead.
func (*PortfolioSlice) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{19}
}

func (x *PortfolioSlice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PortfolioSlice) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PortfolioSlice) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PnLPoint struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Date                  string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	DailyRealizedPnl      float64                `protobuf:"fixed64,2,opt,name=daily_realized_pnl,json=dailyRealizedPnl,proto3" json:"daily_realized_pnl,omitempty"`
	CumulativeRealizedPnl float64                `protobuf:"fixed64,3,opt,name=cumulative_realized_pnl,json=cumulativeRealizedPnl,proto3" json:"cumulative_realized_pnl,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PnLPoint) Reset() {
	*x = PnLPoint{}
	mi := &file_market_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PnLPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PnLPoint) ProtoMessage() {}

func (x *PnLPoint) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PnLPoint.ProtoReflect.Descriptor instead.
func (*PnLPoint) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{20}
}

func (x *PnLPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PnLPoint) GetDailyRealizedPnl() float64 {
	if x != nil {
		return x.DailyRealizedPnl
	}
	return 0
}

func (x *PnLPoint) GetCumulativeRealizedPnl() float64 {
	if x != nil {
		return x.CumulativeRealizedPnl
	}
	return 0
}

type ActivityDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	BuyQuantity   float64                `protobuf:"fixed64,2,opt,name=buy_quantity,json=buyQuantity,proto3" json:"buy_quantity,omitempty"`
	SellQuantity  float64                `protobuf:"fixed64,3,opt,name=sell_quantity,json=sellQuantity,proto3" json:"sell_quantity,omitempty"`
	BuyCount      uint32                 `protobuf:"varint,4,opt,name=buy_count,json=buyCount,proto3" json:"buy_count,omitempty"`
	SellCount     uint32                 `protobuf:"varint,5,opt,name=sell_count,json=sellCount,proto3" json:"sell_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDay) Reset() {
	*x = ActivityDay{}
	mi := &file_market_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDay) ProtoMessage() {}

func (x *ActivityDay) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDay.ProtoReflect.Descriptor instead.
func (*ActivityDay) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{21}
}

func (x *ActivityDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ActivityDay) GetBuyQuantity() float64 {
	if x != nil {
		return x.BuyQuantity
	}
	return 0
}

func (x *ActivityDay) GetSellQuantity() float64 {
	if x != nil {
		return x.SellQuantity
	}
	return 0
}

func (x *ActivityDay) GetBuyCount() uint32 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

func (x *ActivityDay) GetSellCount() uint32 {
	if x != nil {
		return x.SellCount
	}
	return 0
}

type MerchantInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // WINNER, LOSER, STREAK, IDLE, MILESTONE, CONCENTRATION
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	SpiceGradeId  string                 `protobuf:"bytes,4,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"` // optional, empty when portfolio-wide
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`                               // info, success, warning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantInsight) Reset() {
	*x = MerchantInsight{}
	mi := &file_market_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInsight) ProtoMessage() {}

func (x *MerchantInsight) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInsight.ProtoReflect.Descriptor instead.
func (*MerchantInsight) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{22}
}

func (x *MerchantInsight) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MerchantInsight) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MerchantInsight) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MerchantInsight) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *MerchantInsight) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type PriceMover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiceGradeId  string                 `protobuf:"bytes,1,opt,name=spice_grade_id,json=spiceGradeId,proto3" json:"spice_grade_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	GradeName     string                 `protobuf:"bytes,3,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	TodayPrice    float64                `protobuf:"fixed64,4,opt,name=today_price,json=todayPrice,proto3" json:"today_price,omitempty"`
	PreviousPrice float64                `protobuf:"fixed64,5,opt,name=previous_price,json=previousPrice,proto3" json:"previous_price,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,6,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"` // UP, DOWN, FLAT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceMover) Reset() {
	*x = PriceMover{}
	mi := &file_market_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceMover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceMover) ProtoMessage() {}

func (x *PriceMover) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceMover.ProtoReflect.Descriptor instead.
func (*PriceMover) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{23}
}

func (x *PriceMover) GetSpiceGradeId() string {
	if x != nil {
		return x.SpiceGradeId
	}
	return ""
}

func (x *PriceMover) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PriceMover) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *PriceMover) GetTodayPrice() float64 {
	if x != nil {
		return x.TodayPrice
	}
	return 0
}

func (x *PriceMover) GetPreviousPrice() float64 {
	if x != nil {
		return x.PreviousPrice
	}
	return 0
}

func (x *PriceMover) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *PriceMover) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type GetMerchantDashboardResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Summary            *MerchantSummary       `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Holdings           []*MerchantHolding     `protobuf:"bytes,2,rep,name=holdings,proto3" json:"holdings,omitempty"`
	PortfolioMix       []*PortfolioSlice      `protobuf:"bytes,3,rep,name=portfolio_mix,json=portfolioMix,proto3" json:"portfolio_mix,omitempty"`
	PnlTrend           []*PnLPoint            `protobuf:"bytes,4,rep,name=pnl_trend,json=pnlTrend,proto3" json:"pnl_trend,omitempty"`
	ActivityTrend      []*ActivityDay         `protobuf:"bytes,5,rep,name=activity_trend,json=activityTrend,proto3" json:"activity_trend,omitempty"`
	RecentTransactions []*Transaction         `protobuf:"bytes,6,rep,name=recent_transactions,json=recentTransactions,proto3" json:"recent_transactions,omitempty"`
	Insights           []*MerchantInsight     `protobuf:"bytes,7,rep,name=insights,proto3" json:"insights,omitempty"`
	Movers             []*PriceMover          `protobuf:"bytes,8,rep,name=movers,proto3" json:"movers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMerchantDashboardResponse) Reset() {
	*x = GetMerchantDashboardResponse{}
	mi := &file_market_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantDashboardResponse) ProtoMessage() {}

func (x *GetMerchantDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantDashboardResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{24}
}

func (x *GetMerchantDashboardResponse) GetSummary() *MerchantSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetHoldings() []*MerchantHolding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetPortfolioMix() []*PortfolioSlice {
	if x != nil {
		return x.PortfolioMix
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetPnlTrend() []*PnLPoint {
	if x != nil {
		return x.PnlTrend
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetActivityTrend() []*ActivityDay {
	if x != nil {
		return x.ActivityTrend
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetRecentTransactions() []*Transaction {
	if x != nil {
		return x.RecentTransactions
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetInsights() []*MerchantInsight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *GetMerchantDashboardResponse) GetMovers() []*PriceMover {
	if x != nil {
		return x.Movers
	}
	return nil
}

type GetMarketMetricsResponse_TopProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	GradeName     string                 `protobuf:"bytes,2,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketMetricsResponse_TopProduct) Reset() {
	*x = GetMarketMetricsResponse_TopProduct{}
	mi := &file_market_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketMetricsResponse_TopProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketMetricsResponse_TopProduct) ProtoMessage() {}

func (x *GetMarketMetricsResponse_TopProduct) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketMetricsResponse_TopProduct.ProtoReflect.Descriptor instead.
func (*GetMarketMetricsResponse_TopProduct) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{15, 0}
}

func (x *GetMarketMetricsResponse_TopProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *GetMarketMetricsResponse_TopProduct) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *GetMarketMetricsResponse_TopProduct) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x02pb\"\xe0\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x03 \x01(\tR\fspiceGradeId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"trade_date\x18\a \x01(\tR\ttradeDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xae\x02\n" +
	"\fPositionView\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x1b\n" +
	"\ttotal_qty\x18\x03 \x01(\x01R\btotalQty\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12\x19\n" +
	"\bavg_cost\x18\x05 \x01(\x01R\aavgCost\x12\x1f\n" +
	"\vtoday_price\x18\x06 \x01(\x01R\n" +
	"todayPrice\x12!\n" +
	"\frealized_pnl\x18\a \x01(\x01R\vrealizedPnl\x12%\n" +
	"\x0eunrealized_pnl\x18\b \x01(\x01R\runrealizedPnl\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x9c\x01\n" +
	"\n" +
	"BuyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x05 \x01(\tR\ttradeDate\"@\n" +
	"\vBuyResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\"\x9d\x01\n" +
	"\vSellRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x05 \x01(\tR\ttradeDate\"A\n" +
	"\fSellResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\"X\n" +
	"\x17GetGradePositionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\"H\n" +
	"\x18GetGradePositionResponse\x12,\n" +
	"\bposition\x18\x01 \x01(\v2\x10.pb.PositionViewR\bposition\".\n" +
	"\x13GetPositionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x14GetPositionsResponse\x12.\n" +
	"\tpositions\x18\x01 \x03(\v2\x10.pb.PositionViewR\tpositions\"\x85\x01\n" +
	"\x1cListGradeTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0espice_grade_id\x18\x02 \x01(\tR\fspiceGradeId\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x04 \x01(\rR\x04take\"T\n" +
	"\x1dListGradeTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"Z\n" +
	"\x17ListTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\rR\x04skip\x12\x12\n" +
	"\x04take\x18\x03 \x01(\rR\x04take\"O\n" +
	"\x18ListTransactionsResponse\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.pb.TransactionR\ftransactions\"\x19\n" +
	"\x17GetMarketMetricsRequest\"\xa0\x02\n" +
	"\x18GetMarketMetricsResponse\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\rR\x11totalTransactions\x12!\n" +
	"\ftotal_volume\x18\x02 \x01(\x01R\vtotalVolume\x12J\n" +
	"\ftop_products\x18\x03 \x03(\v2'.pb.GetMarketMetricsResponse.TopProductR\vtopProducts\x1af\n" +
	"\n" +
	"TopProduct\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x02 \x01(\tR\tgradeName\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\"1\n" +
	"\x1bGetMerchantDashboardRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\rR\x04days\"\xb3\x03\n" +
	"\x0fMerchantSummary\x12'\n" +
	"\x0fportfolio_value\x18\x01 \x01(\x01R\x0eportfolioValue\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x02 \x01(\x01R\ttotalCost\x12,\n" +
	"\x12total_realized_pnl\x18\x03 \x01(\x01R\x10totalRealizedPnl\x120\n" +
	"\x14total_unrealized_pnl\x18\x04 \x01(\x01R\x12totalUnrealizedPnl\x12\x17\n" +
	"\anet_pnl\x18\x05 \x01(\x01R\x06netPnl\x12%\n" +
	"\x0eopen_positions\x18\x06 \x01(\rR\ropenPositions\x12*\n" +
	"\x11total_quantity_kg\x18\a \x01(\x01R\x0ftotalQuantityKg\x12(\n" +
	"\x10trades_in_period\x18\b \x01(\rR\x0etradesInPeriod\x12/\n" +
	"\x14buy_volume_in_period\x18\t \x01(\x01R\x11buyVolumeInPeriod\x121\n" +
	"\x15sell_volume_in_period\x18\n" +
	" \x01(\x01R\x12sellVolumeInPeriod\"\xba\x03\n" +
	"\x0fMerchantHolding\x12$\n" +
	"\x0espice_grade_id\x18\x01 \x01(\tR\fspiceGradeId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x03 \x01(\tR\tgradeName\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x19\n" +
	"\bavg_cost\x18\x05 \x01(\x01R\aavgCost\x12\x1f\n" +
	"\vtoday_price\x18\x06 \x01(\x01R\n" +
	"todayPrice\x12!\n" +
	"\fmarket_value\x18\a \x01(\x01R\vmarketValue\x12\x1d\n" +
	"\n" +
	"cost_basis\x18\b \x01(\x01R\tcostBasis\x12%\n" +
	"\x0eunrealized_pnl\x18\t \x01(\x01R\runrealizedPnl\x124\n" +
	"\x16unrealized_pnl_percent\x18\n" +
	" \x01(\x01R\x14unrealizedPnlPercent\x12!\n" +
	"\frealized_pnl\x18\v \x01(\x01R\vrealizedPnl\x12%\n" +
	"\x0eweight_percent\x18\f \x01(\x01R\rweightPercent\"X\n" +
	"\x0ePortfolioSlice\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\"\x84\x01\n" +
	"\bPnLPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12,\n" +
	"\x12daily_realized_pnl\x18\x02 \x01(\x01R\x10dailyRealizedPnl\x126\n" +
	"\x17cumulative_realized_pnl\x18\x03 \x01(\x01R\x15cumulativeRealizedPnl\"\xa5\x01\n" +
	"\vActivityDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\fbuy_quantity\x18\x02 \x01(\x01R\vbuyQuantity\x12#\n" +
	"\rsell_quantity\x18\x03 \x01(\x01R\fsellQuantity\x12\x1b\n" +
	"\tbuy_count\x18\x04 \x01(\rR\bbuyCount\x12\x1d\n" +
	"\n" +
	"sell_count\x18\x05 \x01(\rR\tsellCount\"\x91\x01\n" +
	"\x0fMerchantInsight\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12$\n" +
	"\x0espice_grade_id\x18\x04 \x01(\tR\fspiceGradeId\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"\x81\x02\n" +
	"\n" +
	"PriceMover\x12$\n" +
	"\x0espice_grade_id\x18\x01 \x01(\tR\fspiceGradeId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x03 \x01(\tR\tgradeName\x12\x1f\n" +
	"\vtoday_price\x18\x04 \x01(\x01R\n" +
	"todayPrice\x12%\n" +
	"\x0eprevious_price\x18\x05 \x01(\x01R\rpreviousPrice\x12%\n" +
	"\x0echange_percent\x18\x06 \x01(\x01R\rchangePercent\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\"\xb5\x03\n" +
	"\x1cGetMerchantDashboardResponse\x12-\n" +
	"\asummary\x18\x01 \x01(\v2\x13.pb.MerchantSummaryR\asummary\x12/\n" +
	"\bholdings\x18\x02 \x03(\v2\x13.pb.MerchantHoldingR\bholdings\x127\n" +
	"\rportfolio_mix\x18\x03 \x03(\v2\x12.pb.PortfolioSliceR\fportfolioMix\x12)\n" +
	"\tpnl_trend\x18\x04 \x03(\v2\f.pb.PnLPointR\bpnlTrend\x126\n" +
	"\x0eactivity_trend\x18\x05 \x03(\v2\x0f.pb.ActivityDayR\ractivityTrend\x12@\n" +
	"\x13recent_transactions\x18\x06 \x03(\v2\x0f.pb.TransactionR\x12recentTransactions\x12/\n" +
	"\binsights\x18\a \x03(\v2\x13.pb.MerchantInsightR\binsights\x12&\n" +
	"\x06movers\x18\b \x03(\v2\x0e.pb.PriceMoverR\x06movers2\xcb\x04\n" +
	"\rMarketService\x12&\n" +
	"\x03Buy\x12\x0e.pb.BuyRequest\x1a\x0f.pb.BuyResponse\x12)\n" +
	"\x04Sell\x12\x0f.pb.SellRequest\x1a\x10.pb.SellResponse\x12M\n" +
	"\x10GetGradePosition\x12\x1b.pb.GetGradePositionRequest\x1a\x1c.pb.GetGradePositionResponse\x12A\n" +
	"\fGetPositions\x12\x17.pb.GetPositionsRequest\x1a\x18.pb.GetPositionsResponse\x12\\\n" +
	"\x15ListGradeTransactions\x12 .pb.ListGradeTransactionsRequest\x1a!.pb.ListGradeTransactionsResponse\x12M\n" +
	"\x10ListTransactions\x12\x1b.pb.ListTransactionsRequest\x1a\x1c.pb.ListTransactionsResponse\x12M\n" +
	"\x10GetMarketMetrics\x12\x1b.pb.GetMarketMetricsRequest\x1a\x1c.pb.GetMarketMetricsResponse\x12Y\n" +
	"\x14GetMerchantDashboard\x12\x1f.pb.GetMerchantDashboardRequest\x1a .pb.GetMerchantDashboardResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_market_proto_goTypes = []any{
	(*Transaction)(nil),                         // 0: pb.Transaction
	(*PositionView)(nil),                        // 1: pb.PositionView
	(*BuyRequest)(nil),                          // 2: pb.BuyRequest
	(*BuyResponse)(nil),                         // 3: pb.BuyResponse
	(*SellRequest)(nil),                         // 4: pb.SellRequest
	(*SellResponse)(nil),                        // 5: pb.SellResponse
	(*GetGradePositionRequest)(nil),             // 6: pb.GetGradePositionRequest
	(*GetGradePositionResponse)(nil),            // 7: pb.GetGradePositionResponse
	(*GetPositionsRequest)(nil),                 // 8: pb.GetPositionsRequest
	(*GetPositionsResponse)(nil),                // 9: pb.GetPositionsResponse
	(*ListGradeTransactionsRequest)(nil),        // 10: pb.ListGradeTransactionsRequest
	(*ListGradeTransactionsResponse)(nil),       // 11: pb.ListGradeTransactionsResponse
	(*ListTransactionsRequest)(nil),             // 12: pb.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),            // 13: pb.ListTransactionsResponse
	(*GetMarketMetricsRequest)(nil),             // 14: pb.GetMarketMetricsRequest
	(*GetMarketMetricsResponse)(nil),            // 15: pb.GetMarketMetricsResponse
	(*GetMerchantDashboardRequest)(nil),         // 16: pb.GetMerchantDashboardRequest
	(*MerchantSummary)(nil),                     // 17: pb.MerchantSummary
	(*MerchantHolding)(nil),                     // 18: pb.MerchantHolding
	(*PortfolioSlice)(nil),                      // 19: pb.PortfolioSlice
	(*PnLPoint)(nil),                            // 20: pb.PnLPoint
	(*ActivityDay)(nil),                         // 21: pb.ActivityDay
	(*MerchantInsight)(nil),                     // 22: pb.MerchantInsight
	(*PriceMover)(nil),                          // 23: pb.PriceMover
	(*GetMerchantDashboardResponse)(nil),        // 24: pb.GetMerchantDashboardResponse
	(*GetMarketMetricsResponse_TopProduct)(nil), // 25: pb.GetMarketMetricsResponse.TopProduct
}
var file_market_proto_depIdxs = []int32{
	0,  // 0: pb.BuyResponse.transaction:type_name -> pb.Transaction
	0,  // 1: pb.SellResponse.transaction:type_name -> pb.Transaction
	1,  // 2: pb.GetGradePositionResponse.position:type_name -> pb.PositionView
	1,  // 3: pb.GetPositionsResponse.positions:type_name -> pb.PositionView
	0,  // 4: pb.ListGradeTransactionsResponse.transactions:type_name -> pb.Transaction
	0,  // 5: pb.ListTransactionsResponse.transactions:type_name -> pb.Transaction
	25, // 6: pb.GetMarketMetricsResponse.top_products:type_name -> pb.GetMarketMetricsResponse.TopProduct
	17, // 7: pb.GetMerchantDashboardResponse.summary:type_name -> pb.MerchantSummary
	18, // 8: pb.GetMerchantDashboardResponse.holdings:type_name -> pb.MerchantHolding
	19, // 9: pb.GetMerchantDashboardResponse.portfolio_mix:type_name -> pb.PortfolioSlice
	20, // 10: pb.GetMerchantDashboardResponse.pnl_trend:type_name -> pb.PnLPoint
	21, // 11: pb.GetMerchantDashboardResponse.activity_trend:type_name -> pb.ActivityDay
	0,  // 12: pb.GetMerchantDashboardResponse.recent_transactions:type_name -> pb.Transaction
	22, // 13: pb.GetMerchantDashboardResponse.insights:type_name -> pb.MerchantInsight
	23, // 14: pb.GetMerchantDashboardResponse.movers:type_name -> pb.PriceMover
	2,  // 15: pb.MarketService.Buy:input_type -> pb.BuyRequest
	4,  // 16: pb.MarketService.Sell:input_type -> pb.SellRequest
	6,  // 17: pb.MarketService.GetGradePosition:input_type -> pb.GetGradePositionRequest
	8,  // 18: pb.MarketService.GetPositions:input_type -> pb.GetPositionsRequest
	10, // 19: pb.MarketService.ListGradeTransactions:input_type -> pb.ListGradeTransactionsRequest
	12, // 20: pb.MarketService.ListTransactions:input_type -> pb.ListTransactionsRequest
	14, // 21: pb.MarketService.GetMarketMetrics:input_type -> pb.GetMarketMetricsRequest
	16, // 22: pb.MarketService.GetMerchantDashboard:input_type -> pb.GetMerchantDashboardRequest
	3,  // 23: pb.MarketService.Buy:output_type -> pb.BuyResponse
	5,  // 24: pb.MarketService.Sell:output_type -> pb.SellResponse
	7,  // 25: pb.MarketService.GetGradePosition:output_type -> pb.GetGradePositionResponse
	9,  // 26: pb.MarketService.GetPositions:output_type -> pb.GetPositionsResponse
	11, // 27: pb.MarketService.ListGradeTransactions:output_type -> pb.ListGradeTransactionsResponse
	13, // 28: pb.MarketService.ListTransactions:output_type -> pb.ListTransactionsResponse
	15, // 29: pb.MarketService.GetMarketMetrics:output_type -> pb.GetMarketMetricsResponse
	24, // 30: pb.MarketService.GetMerchantDashboard:output_type -> pb.GetMerchantDashboardResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
